In [82]:
import pandas as pd
import pyodbc

In [83]:
import numpy as np

In [ ]:
# Getting the ALP By LDZ(location) (industry data)

In [95]:
server= 'SOE-AWS-SQL-003'
db='soenergy'

conn = pyodbc.connect('DRIVER={SQL Server};SERVER=' + server + ';DATABASE=' + db + '; Trusted_Connection=yes')
sql = "select gldZ.code,gldZ.name,galp.source,galp.validDt,galp.value ALP from soenergy.dbo.UkGasAnnualLoadProfile galp, soenergy.dbo.UkGasFullEndUserCategory feuc, soenergy.dbo.UkGasLocalDistribZone gldZ where galp.ukGasFullEndUserCategoryFk=feuc.id and feuc.ukGasLocalDistribZoneFk=gldZ.id"

ldzAlp = pd.io.sql.read_sql(sql, conn)
ldzAlp

       code           name  source     validDt       ALP
0        SC       Scotland  Actual  2015-10-01  0.709280
1        LC   Campbelltown  Actual  2015-10-01  0.709280
2        LS      Stranraer  Actual  2015-10-01  0.709280
3        LT         Thurso  Actual  2015-10-01  0.709280
4        LO           Oban  Actual  2015-10-01  0.709280
5        LW           Wick  Actual  2015-10-01  0.709280
6        SC       Scotland  Actual  2015-10-02  0.718265
7        LC   Campbelltown  Actual  2015-10-02  0.718265
8        LS      Stranraer  Actual  2015-10-02  0.718265
9        LT         Thurso  Actual  2015-10-02  0.718265
10       LO           Oban  Actual  2015-10-02  0.718265
11       LW           Wick  Actual  2015-10-02  0.718265
12       SC       Scotland  Actual  2015-10-03  0.747919
13       LC   Campbelltown  Actual  2015-10-03  0.747919
14       LS      Stranraer  Actual  2015-10-03  0.747919
15       LT         Thurso  Actual  2015-10-03  0.747919
16       LO           Oban  Actual  2015-10-03  0.747919
17       LW           Wick  Actual  2015-10-03  0.747919
18       SC       Scotland  Actual  2015-10-04  0.775923
19       LC   Campbelltown  Actual  2015-10-04  0.775923
20       LS      Stranraer  Actual  2015-10-04  0.775923
21       LT         Thurso  Actual  2015-10-04  0.775923
22       LO           Oban  Actual  2015-10-04  0.775923
23       LW           Wick  Actual  2015-10-04  0.775923
24       SC       Scotland  Actual  2015-10-05  0.765913
25       LC   Campbelltown  Actual  2015-10-05  0.765913
26       LS      Stranraer  Actual  2015-10-05  0.765913
27       LT         Thurso  Actual  2015-10-05  0.765913
28       LO           Oban  Actual  2015-10-05  0.765913
29       LW           Wick  Actual  2015-10-05  0.765913
...     ...            ...     ...         ...       ...
650530   SW  South Western  Actual  2018-09-01  0.333448
650531   SW  South Western  Actual  2018-09-02  0.332874
650532   SW  South Western  Actual  2018-09-03  0.394037
650533   SW  South Western  Actual  2018-09-04  0.396474
650534   SW  South Western  Actual  2018-09-05  0.398910
650535   SW  South Western  Actual  2018-09-06  0.400129
650536   SW  South Western  Actual  2018-09-07  0.387900
650537   SW  South Western  Actual  2018-09-08  0.345883
650538   SW  South Western  Actual  2018-09-09  0.345217
650539   SW  South Western  Actual  2018-09-10  0.411047
650540   SW  South Western  Actual  2018-09-11  0.415920
650541   SW  South Western  Actual  2018-09-12  0.419551
650542   SW  South Western  Actual  2018-09-13  0.424424
650543   SW  South Western  Actual  2018-09-14  0.413598
650544   SW  South Western  Actual  2018-09-15  0.373902
650545   SW  South Western  Actual  2018-09-16  0.376109
650546   SW  South Western  Actual  2018-09-17  0.449938
650547   SW  South Western  Actual  2018-09-18  0.456006
650548   SW  South Western  Actual  2018-09-19  0.462097
650549   SW  South Western  Actual  2018-09-20  0.468165
650550   SW  South Western  Actual  2018-09-21  0.455615
650551   SW  South Western  Actual  2018-09-22  0.411276
650552   SW  South Western  Actual  2018-09-23  0.415230
650553   SW  South Western  Actual  2018-09-24  0.497334
650554   SW  South Western  Actual  2018-09-25  0.507056
650555   SW  South Western  Actual  2018-09-26  0.516756
650556   SW  South Western  Actual  2018-09-27  0.527697
650557   SW  South Western  Actual  2018-09-28  0.519813
650558   SW  South Western  Actual  2018-09-29  0.474578
650559   SW  South Western  Actual  2018-09-30  0.483198

[650560 rows x 5 columns]

In [85]:
import pandas as pd
import numpy as np
import csv

In [86]:
# ldzAlp = pd.read_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/ldzALP.csv')

In [96]:
ldzAlp.drop_duplicates(subset=['code','validDt'], inplace = True)

In [97]:
ldzAlp

       code           name  source     validDt       ALP
0        SC       Scotland  Actual  2015-10-01  0.709280
1        LC   Campbelltown  Actual  2015-10-01  0.709280
2        LS      Stranraer  Actual  2015-10-01  0.709280
3        LT         Thurso  Actual  2015-10-01  0.709280
4        LO           Oban  Actual  2015-10-01  0.709280
5        LW           Wick  Actual  2015-10-01  0.709280
6        SC       Scotland  Actual  2015-10-02  0.718265
7        LC   Campbelltown  Actual  2015-10-02  0.718265
8        LS      Stranraer  Actual  2015-10-02  0.718265
9        LT         Thurso  Actual  2015-10-02  0.718265
10       LO           Oban  Actual  2015-10-02  0.718265
11       LW           Wick  Actual  2015-10-02  0.718265
12       SC       Scotland  Actual  2015-10-03  0.747919
13       LC   Campbelltown  Actual  2015-10-03  0.747919
14       LS      Stranraer  Actual  2015-10-03  0.747919
15       LT         Thurso  Actual  2015-10-03  0.747919
16       LO           Oban  Actual  2015-10-03  0.747919
17       LW           Wick  Actual  2015-10-03  0.747919
18       SC       Scotland  Actual  2015-10-04  0.775923
19       LC   Campbelltown  Actual  2015-10-04  0.775923
20       LS      Stranraer  Actual  2015-10-04  0.775923
21       LT         Thurso  Actual  2015-10-04  0.775923
22       LO           Oban  Actual  2015-10-04  0.775923
23       LW           Wick  Actual  2015-10-04  0.775923
24       SC       Scotland  Actual  2015-10-05  0.765913
25       LC   Campbelltown  Actual  2015-10-05  0.765913
26       LS      Stranraer  Actual  2015-10-05  0.765913
27       LT         Thurso  Actual  2015-10-05  0.765913
28       LO           Oban  Actual  2015-10-05  0.765913
29       LW           Wick  Actual  2015-10-05  0.765913
...     ...            ...     ...         ...       ...
440290   SW  South Western  Actual  2018-09-01  0.272497
440291   SW  South Western  Actual  2018-09-02  0.274092
440292   SW  South Western  Actual  2018-09-03  0.268172
440293   SW  South Western  Actual  2018-09-04  0.271263
440294   SW  South Western  Actual  2018-09-05  0.274353
440295   SW  South Western  Actual  2018-09-06  0.275899
440296   SW  South Western  Actual  2018-09-07  0.284735
440297   SW  South Western  Actual  2018-09-08  0.291664
440298   SW  South Western  Actual  2018-09-09  0.293147
440299   SW  South Western  Actual  2018-09-10  0.289795
440300   SW  South Western  Actual  2018-09-11  0.295976
440301   SW  South Western  Actual  2018-09-12  0.300612
440302   SW  South Western  Actual  2018-09-13  0.306794
440303   SW  South Western  Actual  2018-09-14  0.319232
440304   SW  South Western  Actual  2018-09-15  0.334785
440305   SW  South Western  Actual  2018-09-16  0.340780
440306   SW  South Western  Actual  2018-09-17  0.339222
440307   SW  South Western  Actual  2018-09-18  0.346949
440308   SW  South Western  Actual  2018-09-19  0.354675
440309   SW  South Western  Actual  2018-09-20  0.362390
440310   SW  South Western  Actual  2018-09-21  0.375675
440311   SW  South Western  Actual  2018-09-22  0.392288
440312   SW  South Western  Actual  2018-09-23  0.401124
440313   SW  South Western  Actual  2018-09-24  0.399466
440314   SW  South Western  Actual  2018-09-25  0.411829
440315   SW  South Western  Actual  2018-09-26  0.424180
440316   SW  South Western  Actual  2018-09-27  0.438088
440317   SW  South Western  Actual  2018-09-28  0.461904
440318   SW  South Western  Actual  2018-09-29  0.489709
440319   SW  South Western  Actual  2018-09-30  0.505923

[19728 rows x 5 columns]

In [89]:
mprnusage = pd.read_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/NEW_MPRN_USAGE.csv')

In [90]:
mprnusage

,meterPointIdentifier,SerialNum,eventDttm,cumulative,mrmr,LDZ,STAT
0,1000029807,E6S09061321756,14/02/2018,99999.0,NaN,SC,Accepted
1,1000029807,E6S09061321756,07/08/2018,567.0,8.0,SC,Accepted
2,1000029807,E6S03043551556,06/06/2016,1431.0,8.0,SC,Accepted
3,1000029807,E6S03043551556,04/01/2016,593.0,8.0,SC,Accepted
4,1000029807,E6S09061321756,24/05/2018,487.0,8.0,SC,Accepted
5,1000029807,E6S03043551556,13/09/2016,1619.0,NaN,SC,Accepted
6,1000029807,E6S03043551556,21/08/2017,2985.0,NaN,SC,Accepted
7,1000029807,E6S03043551556,09/03/2016,1071.0,8.0,SC,Accepted
8,1000029807,E6S03043551556,10/03/2016,1075.0,NaN,SC,Accepted
9,1000029807,E6S03043551556,12/08/2017,2970.0,8.0,SC,Accepted
10,1000041909,G4A50109761601,04/04/2018,1848.0,8.0,SC,Accepted
11,1000041909,G4A50109761601,20/04/2018,1944.0,8.0,SC,Accepted
12,1000041909,G4A50109761601,23/07/2018,2148.0,8.0,SC,Accepted
13,1000041909,5029504S,16/12/2016,2168.0,14.0,SC,Accepted
14,1000041909,5029504S,20/02/2017,2375.0,14.0,SC,Accepted
15,1000041909,G4A50109761601,29/11/2017,681.0,8.0,SC,Accepted
16,1000041909,5029504S,24/11/2016,2104.0,14.0,SC,Accepted
17,1000041909,G4A50109761601,24/02/2018,1517.0,8.0,SC,Accepted
18,1000041909,5029504S,23/10/2016,2023.0,14.0,SC,Accepted
19,1000041909,5029504S,23/05/2017,2561.0,14.0,SC,Accepted
20,1000041909,G4A50109761601,29/01/2018,1282.0,8.0,SC,Accepted
21,1000041909,5029504S,10/05/2017,2543.0,14.0,SC,Accepted
22,1000041909,G4A50109761601,29/08/2017,224.0,8.0,SC,Accepted
23,1000041909,G4A50109761601,19/09/2017,297.0,8.0,SC,Accepted
24,1000041909,G4A50109761601,27/06/2017,80.0,8.0,SC,Accepted
25,1000041909,G4A50109761601,23/05/2017,0.0,NaN,SC,Accepted
26,1000041909,5029504S,16/03/2017,2439.0,14.0,SC,Accepted
27,1000041909,5029504S,10/04/2017,2490.0,NaN,SC,Accepted
28,1000041909,G4A50109761601,05/11/2017,508.0,8.0,SC,Accepted
29,1000041909,G4A50109761601,18/06/2018,2111.0,8.0,SC,Accepted
...,...,...,...,...,...,...,...
339914,9364510501,E6S06247081756,25/03/2018,519.0,8.0,EM,Accepted
339915,9364510501,E6S06247081756,25/07/2018,847.0,8.0,EM,Accepted
339916,9364510501,E6S06247081756,06/02/2018,0.0,8.0,EM,Accepted
339917,9364510501,E6S06247081756,25/04/2018,730.0,8.0,EM,Accepted
339918,9364779007,E6S01263690852,26/06/2018,5659.0,8.0,SC,Accepted
339919,9364899410,M016K0654815D6,07/06/2018,6414.0,8.0,SO,Accepted
339920,9365381207,G4K10362850201,06/08/2018,21602.0,8.0,EA,Accepted
339921,9365381207,G4K10362850201,06/07/2018,21590.0,8.0,EA,Accepted
339922,9365381207,G4K10362850201,29/07/2018,21598.0,8.0,EA,Accepted
339923,9365381207,G4K10362850201,07/05/2018,21549.0,NaN,EA,Accepted
339924,9365381207,G4K10362850201,16/06/2018,21580.0,8.0,EA,Accepted
339925,9365381207,G4K10362850201,04/06/2018,21572.0,8.0,EA,Accepted
339926,9365381207,G4K10362850201,08/06/2018,21575.0,8.0,EA,Accepted
339927,9365848802,G4A00135409901,06/08/2018,15949.0,8.0,SW,Accepted
339928,9365848802,G4A00135409901,06/04/2018,15748.0,8.0,SW,Accepted
339929,9365848802,G4A00135409901,02/07/2018,15923.0,8.0,SW,Accepted
339930,9365848802,G4A00135409901,07/05/2018,15828.0,8.0,SW,Accepted
339931,9365848802,G4A00135409901,07/06/2018,15900.0,8.0,SW,Accepted
339932,9366727402,G4K51501751601,05/07/2018,2128.0,8.0,EA,Accepted
339933,9366727402,G4K51501751601,03/05/2018,2009.0,8.0,EA,Accepted
339934,9366729002,G4W00525150701,07/05/2018,36496.0,8.0,WM,Accepted
339935,9366729002,G4W00525150701,06/08/2018,36712.0,8.0,WM,Accepted
339936,9366729002,G4W00525150701,07/03/2018,35822.0,8.0,WM,Accepted
339937,9366729002,G4W00525150701,06/04/2018,36236.0,8.0,WM,Accepted
339938,9366729002,G4W00525150701,06/07/2018,36680.0,8.0,WM,Accepted
339939,9366729002,G4W00525150701,06/02/2018,35296.0,8.0,WM,Accepted
339940,9366729002,G4W00525150701,08/06/2018,36609.0,8.0,WM,Accepted
339941,9366729002,G4W00525150701,23/01/2018,34967.0,NaN,WM,Accepted
339942,9367103907,G4W01732390902,10/05/2018,4551.0,8.0,EA,Accepted
339943,9367526610,G4K64934450611,02/07/2018,20167.0,8.0,SC,Accepted

In [91]:
mprnusage['eventDttm'] = pd.to_datetime(mprnusage['eventDttm'])

In [92]:
jDF = pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [93]:
for _, i in mprnusage.groupby(['meterPointIdentifier','SerialNum']):
    i = i.sort_values('eventDttm')
    jDF = jDF.append(i)

jDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,mrmr,LDZ,STAT
11931,11006910,G4K00362451701,2018-03-03,0.0,NaN,SW,Accepted
11928,11006910,G4K00362451701,2018-06-18,996.0,8.0,SW,Accepted
11932,11006910,G4K01864940101,2016-12-28,49806.0,8.0,SW,Accepted
11930,11006910,G4K01864940101,2017-03-14,50806.0,NaN,SW,Accepted
11927,11006910,G4K01864940101,2017-09-20,51695.0,NaN,SW,Accepted
11929,11006910,G4K01864940101,2018-03-03,53973.0,NaN,SW,Accepted
21217,12807108,G4K68050890714,2016-04-29,11288.0,8.0,NW,Accepted
21218,12807108,G4K68050890714,2016-06-07,11557.0,NaN,NW,Accepted
21216,12807108,G4K68050890714,2016-12-16,12623.0,NaN,NW,Accepted
21219,12807108,G4K68050890714,2017-04-25,14901.0,8.0,NW,Accepted
21220,12807108,G4K68050890714,2017-06-22,15086.0,NaN,NW,Accepted
21221,12807108,G4K68050890714,2018-04-16,18810.0,NaN,NW,Accepted
23561,12992601,G4A00290751301,2016-08-20,3050.0,8.0,SE,Accepted
23576,12992601,G4A00290751301,2016-09-15,3064.0,8.0,SE,Accepted
23570,12992601,G4A00290751301,2016-10-16,3108.0,8.0,SE,Accepted
23568,12992601,G4A00290751301,2016-11-20,3203.0,8.0,SE,Accepted
23567,12992601,G4A00290751301,2016-12-22,3278.0,8.0,SE,Accepted
23571,12992601,G4A00290751301,2017-01-28,3420.0,8.0,SE,Accepted
23572,12992601,G4A00290751301,2017-03-22,3570.0,8.0,SE,Accepted
23573,12992601,G4A00290751301,2017-03-29,3584.0,NaN,SE,Accepted
23565,12992601,G4A00290751301,2017-04-14,3597.0,8.0,SE,Accepted
23574,12992601,G4A00290751301,2017-04-27,3622.0,8.0,SE,Accepted
23577,12992601,G4A00290751301,2017-07-20,3679.0,8.0,SE,Accepted
23575,12992601,G4A00290751301,2017-08-17,3696.0,8.0,SE,Accepted
23566,12992601,G4A00290751301,2017-09-27,3715.0,NaN,SE,Accepted
23563,12992601,G4A00290751301,2017-12-21,3987.0,8.0,SE,Accepted
23569,12992601,G4A00290751301,2018-02-19,4541.0,8.0,SE,Accepted
23564,12992601,G4A00290751301,2018-06-02,4398.0,8.0,SE,Accepted
23562,12992601,G4A00290751301,2018-06-30,4966.0,8.0,SE,Accepted
53358,15821701,G4P01032961600,2016-02-12,1011.0,NaN,NW,Accepted
...,...,...,...,...,...,...,...
339911,9364510501,E6S06247081756,2018-05-25,810.0,8.0,EM,Accepted
339916,9364510501,E6S06247081756,2018-06-02,0.0,8.0,EM,Accepted
339913,9364510501,E6S06247081756,2018-06-25,831.0,8.0,EM,Accepted
339915,9364510501,E6S06247081756,2018-07-25,847.0,8.0,EM,Accepted
339918,9364779007,E6S01263690852,2018-06-26,5659.0,8.0,SC,Accepted
339919,9364899410,M016K0654815D6,2018-07-06,6414.0,8.0,SO,Accepted
339925,9365381207,G4K10362850201,2018-04-06,21572.0,8.0,EA,Accepted
339921,9365381207,G4K10362850201,2018-06-07,21590.0,8.0,EA,Accepted
339920,9365381207,G4K10362850201,2018-06-08,21602.0,8.0,EA,Accepted
339924,9365381207,G4K10362850201,2018-06-16,21580.0,8.0,EA,Accepted
339923,9365381207,G4K10362850201,2018-07-05,21549.0,NaN,EA,Accepted
339922,9365381207,G4K10362850201,2018-07-29,21598.0,8.0,EA,Accepted
339926,9365381207,G4K10362850201,2018-08-06,21575.0,8.0,EA,Accepted
339929,9365848802,G4A00135409901,2018-02-07,15923.0,8.0,SW,Accepted
339928,9365848802,G4A00135409901,2018-06-04,15748.0,8.0,SW,Accepted
339927,9365848802,G4A00135409901,2018-06-08,15949.0,8.0,SW,Accepted
339930,9365848802,G4A00135409901,2018-07-05,15828.0,8.0,SW,Accepted
339931,9365848802,G4A00135409901,2018-07-06,15900.0,8.0,SW,Accepted
339933,9366727402,G4K51501751601,2018-03-05,2009.0,8.0,EA,Accepted
339932,9366727402,G4K51501751601,2018-05-07,2128.0,8.0,EA,Accepted
339941,9366729002,G4W00525150701,2018-01-23,34967.0,NaN,WM,Accepted
339939,9366729002,G4W00525150701,2018-06-02,35296.0,8.0,WM,Accepted
339937,9366729002,G4W00525150701,2018-06-04,36236.0,8.0,WM,Accepted
339938,9366729002,G4W00525150701,2018-06-07,36680.0,8.0,WM,Accepted
339935,9366729002,G4W00525150701,2018-06-08,36712.0,8.0,WM,Accepted
339936,9366729002,G4W00525150701,2018-07-03,35822.0,8.0,WM,Accepted
339934,9366729002,G4W00525150701,2018-07-05,36496.0,8.0,WM,Accepted
339940,9366729002,G4W00525150701,2018-08-06,36609.0,8.0,WM,Accepted
339942,9367103907,G4W01732390902,2018-10-05,4551.0,8.0,EA,Accepted
339943,9367526610,G4K64934450611,2018-02-07,20167.0,8.0,SC,Accepted

In [98]:
jDF.reset_index(drop=True, inplace=True)

In [99]:
jDF['len'] = np.nan

In [100]:
mask = ~jDF['meterPointIdentifier'].duplicated(keep='first')
mask

0          True
1         False
2         False
3         False
4         False
5         False
6          True
7         False
8         False
9         False
10        False
11        False
12         True
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29         True
          ...
339914    False
339915    False
339916    False
339917    False
339918     True
339919     True
339920     True
339921    False
339922    False
339923    False
339924    False
339925    False
339926    False
339927     True
339928    False
339929    False
339930    False
339931    False
339932     True
339933    False
339934     True
339935    False
339936    False
339937    False
339938    False
339939    False
339940    False
339941    False
339942     True
339943     True
Name: meterPointIdentifier, Length: 339944, dtype: bool

In [101]:
jDF.loc[mask,'len'] = 0

In [102]:
jDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,mrmr,LDZ,STAT,len
0,11006910,G4K00362451701,2018-03-03,0.0,NaN,SW,Accepted,0.0
1,11006910,G4K00362451701,2018-06-18,996.0,8.0,SW,Accepted,NaN
2,11006910,G4K01864940101,2016-12-28,49806.0,8.0,SW,Accepted,NaN
3,11006910,G4K01864940101,2017-03-14,50806.0,NaN,SW,Accepted,NaN
4,11006910,G4K01864940101,2017-09-20,51695.0,NaN,SW,Accepted,NaN
5,11006910,G4K01864940101,2018-03-03,53973.0,NaN,SW,Accepted,NaN
6,12807108,G4K68050890714,2016-04-29,11288.0,8.0,NW,Accepted,0.0
7,12807108,G4K68050890714,2016-06-07,11557.0,NaN,NW,Accepted,NaN
8,12807108,G4K68050890714,2016-12-16,12623.0,NaN,NW,Accepted,NaN
9,12807108,G4K68050890714,2017-04-25,14901.0,8.0,NW,Accepted,NaN
10,12807108,G4K68050890714,2017-06-22,15086.0,NaN,NW,Accepted,NaN
11,12807108,G4K68050890714,2018-04-16,18810.0,NaN,NW,Accepted,NaN
12,12992601,G4A00290751301,2016-08-20,3050.0,8.0,SE,Accepted,0.0
13,12992601,G4A00290751301,2016-09-15,3064.0,8.0,SE,Accepted,NaN
14,12992601,G4A00290751301,2016-10-16,3108.0,8.0,SE,Accepted,NaN
15,12992601,G4A00290751301,2016-11-20,3203.0,8.0,SE,Accepted,NaN
16,12992601,G4A00290751301,2016-12-22,3278.0,8.0,SE,Accepted,NaN
17,12992601,G4A00290751301,2017-01-28,3420.0,8.0,SE,Accepted,NaN
18,12992601,G4A00290751301,2017-03-22,3570.0,8.0,SE,Accepted,NaN
19,12992601,G4A00290751301,2017-03-29,3584.0,NaN,SE,Accepted,NaN
20,12992601,G4A00290751301,2017-04-14,3597.0,8.0,SE,Accepted,NaN
21,12992601,G4A00290751301,2017-04-27,3622.0,8.0,SE,Accepted,NaN
22,12992601,G4A00290751301,2017-07-20,3679.0,8.0,SE,Accepted,NaN
23,12992601,G4A00290751301,2017-08-17,3696.0,8.0,SE,Accepted,NaN
24,12992601,G4A00290751301,2017-09-27,3715.0,NaN,SE,Accepted,NaN
25,12992601,G4A00290751301,2017-12-21,3987.0,8.0,SE,Accepted,NaN
26,12992601,G4A00290751301,2018-02-19,4541.0,8.0,SE,Accepted,NaN
27,12992601,G4A00290751301,2018-06-02,4398.0,8.0,SE,Accepted,NaN
28,12992601,G4A00290751301,2018-06-30,4966.0,8.0,SE,Accepted,NaN
29,15821701,G4P01032961600,2016-02-12,1011.0,NaN,NW,Accepted,0.0
...,...,...,...,...,...,...,...,...
339914,9364510501,E6S06247081756,2018-05-25,810.0,8.0,EM,Accepted,NaN
339915,9364510501,E6S06247081756,2018-06-02,0.0,8.0,EM,Accepted,NaN
339916,9364510501,E6S06247081756,2018-06-25,831.0,8.0,EM,Accepted,NaN
339917,9364510501,E6S06247081756,2018-07-25,847.0,8.0,EM,Accepted,NaN
339918,9364779007,E6S01263690852,2018-06-26,5659.0,8.0,SC,Accepted,0.0
339919,9364899410,M016K0654815D6,2018-07-06,6414.0,8.0,SO,Accepted,0.0
339920,9365381207,G4K10362850201,2018-04-06,21572.0,8.0,EA,Accepted,0.0
339921,9365381207,G4K10362850201,2018-06-07,21590.0,8.0,EA,Accepted,NaN
339922,9365381207,G4K10362850201,2018-06-08,21602.0,8.0,EA,Accepted,NaN
339923,9365381207,G4K10362850201,2018-06-16,21580.0,8.0,EA,Accepted,NaN
339924,9365381207,G4K10362850201,2018-07-05,21549.0,NaN,EA,Accepted,NaN
339925,9365381207,G4K10362850201,2018-07-29,21598.0,8.0,EA,Accepted,NaN
339926,9365381207,G4K10362850201,2018-08-06,21575.0,8.0,EA,Accepted,NaN
339927,9365848802,G4A00135409901,2018-02-07,15923.0,8.0,SW,Accepted,0.0
339928,9365848802,G4A00135409901,2018-06-04,15748.0,8.0,SW,Accepted,NaN
339929,9365848802,G4A00135409901,2018-06-08,15949.0,8.0,SW,Accepted,NaN
339930,9365848802,G4A00135409901,2018-07-05,15828.0,8.0,SW,Accepted,NaN
339931,9365848802,G4A00135409901,2018-07-06,15900.0,8.0,SW,Accepted,NaN
339932,9366727402,G4K51501751601,2018-03-05,2009.0,8.0,EA,Accepted,0.0
339933,9366727402,G4K51501751601,2018-05-07,2128.0,8.0,EA,Accepted,NaN
339934,9366729002,G4W00525150701,2018-01-23,34967.0,NaN,WM,Accepted,0.0
339935,9366729002,G4W00525150701,2018-06-02,35296.0,8.0,WM,Accepted,NaN
339936,9366729002,G4W00525150701,2018-06-04,36236.0,8.0,WM,Accepted,NaN
339937,9366729002,G4W00525150701,2018-06-07,36680.0,8.0,WM,Accepted,NaN
339938,9366729002,G4W00525150701,2018-06-08,36712.0,8.0,WM,Accepted,NaN
339939,9366729002,G4W00525150701,2018-07-03,35822.0,8.0,WM,Accepted,NaN
339940,9366729002,G4W00525150701,2018-07-05,36496.0,8.0,WM,Accepted,NaN
339941,9366729002,G4W00525150701,2018-08-06,36609.0,8.0,WM,Accepted,NaN
339942,9367103907,G4W01732390902,2018-10-05,4551.0,8.0,EA,Accepted,0.0
339943,9367526610,G4K64934450611,2018-02-07,20167.0,8.0,SC,Accepted,0.0

In [103]:
error_mask = (jDF['cumulative'] <= jDF['cumulative'].shift(1)) & (jDF['len']!=0)
jDF.loc[error_mask, 'error'] = True

In [104]:
jDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,mrmr,LDZ,STAT,len,error
0,11006910,G4K00362451701,2018-03-03,0.0,NaN,SW,Accepted,0.0,NaN
1,11006910,G4K00362451701,2018-06-18,996.0,8.0,SW,Accepted,NaN,NaN
2,11006910,G4K01864940101,2016-12-28,49806.0,8.0,SW,Accepted,NaN,NaN
3,11006910,G4K01864940101,2017-03-14,50806.0,NaN,SW,Accepted,NaN,NaN
4,11006910,G4K01864940101,2017-09-20,51695.0,NaN,SW,Accepted,NaN,NaN
5,11006910,G4K01864940101,2018-03-03,53973.0,NaN,SW,Accepted,NaN,NaN
6,12807108,G4K68050890714,2016-04-29,11288.0,8.0,NW,Accepted,0.0,NaN
7,12807108,G4K68050890714,2016-06-07,11557.0,NaN,NW,Accepted,NaN,NaN
8,12807108,G4K68050890714,2016-12-16,12623.0,NaN,NW,Accepted,NaN,NaN
9,12807108,G4K68050890714,2017-04-25,14901.0,8.0,NW,Accepted,NaN,NaN
10,12807108,G4K68050890714,2017-06-22,15086.0,NaN,NW,Accepted,NaN,NaN
11,12807108,G4K68050890714,2018-04-16,18810.0,NaN,NW,Accepted,NaN,NaN
12,12992601,G4A00290751301,2016-08-20,3050.0,8.0,SE,Accepted,0.0,NaN
13,12992601,G4A00290751301,2016-09-15,3064.0,8.0,SE,Accepted,NaN,NaN
14,12992601,G4A00290751301,2016-10-16,3108.0,8.0,SE,Accepted,NaN,NaN
15,12992601,G4A00290751301,2016-11-20,3203.0,8.0,SE,Accepted,NaN,NaN
16,12992601,G4A00290751301,2016-12-22,3278.0,8.0,SE,Accepted,NaN,NaN
17,12992601,G4A00290751301,2017-01-28,3420.0,8.0,SE,Accepted,NaN,NaN
18,12992601,G4A00290751301,2017-03-22,3570.0,8.0,SE,Accepted,NaN,NaN
19,12992601,G4A00290751301,2017-03-29,3584.0,NaN,SE,Accepted,NaN,NaN
20,12992601,G4A00290751301,2017-04-14,3597.0,8.0,SE,Accepted,NaN,NaN
21,12992601,G4A00290751301,2017-04-27,3622.0,8.0,SE,Accepted,NaN,NaN
22,12992601,G4A00290751301,2017-07-20,3679.0,8.0,SE,Accepted,NaN,NaN
23,12992601,G4A00290751301,2017-08-17,3696.0,8.0,SE,Accepted,NaN,NaN
24,12992601,G4A00290751301,2017-09-27,3715.0,NaN,SE,Accepted,NaN,NaN
25,12992601,G4A00290751301,2017-12-21,3987.0,8.0,SE,Accepted,NaN,NaN
26,12992601,G4A00290751301,2018-02-19,4541.0,8.0,SE,Accepted,NaN,NaN
27,12992601,G4A00290751301,2018-06-02,4398.0,8.0,SE,Accepted,NaN,True
28,12992601,G4A00290751301,2018-06-30,4966.0,8.0,SE,Accepted,NaN,NaN
29,15821701,G4P01032961600,2016-02-12,1011.0,NaN,NW,Accepted,0.0,NaN
...,...,...,...,...,...,...,...,...,...
339914,9364510501,E6S06247081756,2018-05-25,810.0,8.0,EM,Accepted,NaN,NaN
339915,9364510501,E6S06247081756,2018-06-02,0.0,8.0,EM,Accepted,NaN,True
339916,9364510501,E6S06247081756,2018-06-25,831.0,8.0,EM,Accepted,NaN,NaN
339917,9364510501,E6S06247081756,2018-07-25,847.0,8.0,EM,Accepted,NaN,NaN
339918,9364779007,E6S01263690852,2018-06-26,5659.0,8.0,SC,Accepted,0.0,NaN
339919,9364899410,M016K0654815D6,2018-07-06,6414.0,8.0,SO,Accepted,0.0,NaN
339920,9365381207,G4K10362850201,2018-04-06,21572.0,8.0,EA,Accepted,0.0,NaN
339921,9365381207,G4K10362850201,2018-06-07,21590.0,8.0,EA,Accepted,NaN,NaN
339922,9365381207,G4K10362850201,2018-06-08,21602.0,8.0,EA,Accepted,NaN,NaN
339923,9365381207,G4K10362850201,2018-06-16,21580.0,8.0,EA,Accepted,NaN,True
339924,9365381207,G4K10362850201,2018-07-05,21549.0,NaN,EA,Accepted,NaN,True
339925,9365381207,G4K10362850201,2018-07-29,21598.0,8.0,EA,Accepted,NaN,NaN
339926,9365381207,G4K10362850201,2018-08-06,21575.0,8.0,EA,Accepted,NaN,True
339927,9365848802,G4A00135409901,2018-02-07,15923.0,8.0,SW,Accepted,0.0,NaN
339928,9365848802,G4A00135409901,2018-06-04,15748.0,8.0,SW,Accepted,NaN,True
339929,9365848802,G4A00135409901,2018-06-08,15949.0,8.0,SW,Accepted,NaN,NaN
339930,9365848802,G4A00135409901,2018-07-05,15828.0,8.0,SW,Accepted,NaN,True
339931,9365848802,G4A00135409901,2018-07-06,15900.0,8.0,SW,Accepted,NaN,NaN
339932,9366727402,G4K51501751601,2018-03-05,2009.0,8.0,EA,Accepted,0.0,NaN
339933,9366727402,G4K51501751601,2018-05-07,2128.0,8.0,EA,Accepted,NaN,NaN
339934,9366729002,G4W00525150701,2018-01-23,34967.0,NaN,WM,Accepted,0.0,NaN
339935,9366729002,G4W00525150701,2018-06-02,35296.0,8.0,WM,Accepted,NaN,NaN
339936,9366729002,G4W00525150701,2018-06-04,36236.0,8.0,WM,Accepted,NaN,NaN
339937,9366729002,G4W00525150701,2018-06-07,36680.0,8.0,WM,Accepted,NaN,NaN
339938,9366729002,G4W00525150701,2018-06-08,36712.0,8.0,WM,Accepted,NaN,NaN
339939,9366729002,G4W00525150701,2018-07-03,35822.0,8.0,WM,Accepted,NaN,True
339940,9366729002,G4W00525150701,2018-07-05,36496.0,8.0,WM,Accepted,NaN,NaN
339941,9366729002,G4W00525150701,2018-08-06,36609.0,8.0,WM,Accepted,NaN,NaN
339942,9367103907,G4W01732390902,2018-10-05,4551.0,8.0,EA,Accepted,0.0,NaN
339943,9367526610,G4K64934450611,2018-02-07,20167.0,8.0,SC,Accepted,0.0,NaN

In [105]:
jDF['lenall'] = 10**jDF['cumulative'].astype(int).astype(str).str.len()

In [106]:
jDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,mrmr,LDZ,STAT,len,error,lenall
0,11006910,G4K00362451701,2018-03-03,0.0,NaN,SW,Accepted,0.0,NaN,10
1,11006910,G4K00362451701,2018-06-18,996.0,8.0,SW,Accepted,NaN,NaN,1000
2,11006910,G4K01864940101,2016-12-28,49806.0,8.0,SW,Accepted,NaN,NaN,100000
3,11006910,G4K01864940101,2017-03-14,50806.0,NaN,SW,Accepted,NaN,NaN,100000
4,11006910,G4K01864940101,2017-09-20,51695.0,NaN,SW,Accepted,NaN,NaN,100000
5,11006910,G4K01864940101,2018-03-03,53973.0,NaN,SW,Accepted,NaN,NaN,100000
6,12807108,G4K68050890714,2016-04-29,11288.0,8.0,NW,Accepted,0.0,NaN,100000
7,12807108,G4K68050890714,2016-06-07,11557.0,NaN,NW,Accepted,NaN,NaN,100000
8,12807108,G4K68050890714,2016-12-16,12623.0,NaN,NW,Accepted,NaN,NaN,100000
9,12807108,G4K68050890714,2017-04-25,14901.0,8.0,NW,Accepted,NaN,NaN,100000
10,12807108,G4K68050890714,2017-06-22,15086.0,NaN,NW,Accepted,NaN,NaN,100000
11,12807108,G4K68050890714,2018-04-16,18810.0,NaN,NW,Accepted,NaN,NaN,100000
12,12992601,G4A00290751301,2016-08-20,3050.0,8.0,SE,Accepted,0.0,NaN,10000
13,12992601,G4A00290751301,2016-09-15,3064.0,8.0,SE,Accepted,NaN,NaN,10000
14,12992601,G4A00290751301,2016-10-16,3108.0,8.0,SE,Accepted,NaN,NaN,10000
15,12992601,G4A00290751301,2016-11-20,3203.0,8.0,SE,Accepted,NaN,NaN,10000
16,12992601,G4A00290751301,2016-12-22,3278.0,8.0,SE,Accepted,NaN,NaN,10000
17,12992601,G4A00290751301,2017-01-28,3420.0,8.0,SE,Accepted,NaN,NaN,10000
18,12992601,G4A00290751301,2017-03-22,3570.0,8.0,SE,Accepted,NaN,NaN,10000
19,12992601,G4A00290751301,2017-03-29,3584.0,NaN,SE,Accepted,NaN,NaN,10000
20,12992601,G4A00290751301,2017-04-14,3597.0,8.0,SE,Accepted,NaN,NaN,10000
21,12992601,G4A00290751301,2017-04-27,3622.0,8.0,SE,Accepted,NaN,NaN,10000
22,12992601,G4A00290751301,2017-07-20,3679.0,8.0,SE,Accepted,NaN,NaN,10000
23,12992601,G4A00290751301,2017-08-17,3696.0,8.0,SE,Accepted,NaN,NaN,10000
24,12992601,G4A00290751301,2017-09-27,3715.0,NaN,SE,Accepted,NaN,NaN,10000
25,12992601,G4A00290751301,2017-12-21,3987.0,8.0,SE,Accepted,NaN,NaN,10000
26,12992601,G4A00290751301,2018-02-19,4541.0,8.0,SE,Accepted,NaN,NaN,10000
27,12992601,G4A00290751301,2018-06-02,4398.0,8.0,SE,Accepted,NaN,True,10000
28,12992601,G4A00290751301,2018-06-30,4966.0,8.0,SE,Accepted,NaN,NaN,10000
29,15821701,G4P01032961600,2016-02-12,1011.0,NaN,NW,Accepted,0.0,NaN,10000
...,...,...,...,...,...,...,...,...,...,...
339914,9364510501,E6S06247081756,2018-05-25,810.0,8.0,EM,Accepted,NaN,NaN,1000
339915,9364510501,E6S06247081756,2018-06-02,0.0,8.0,EM,Accepted,NaN,True,10
339916,9364510501,E6S06247081756,2018-06-25,831.0,8.0,EM,Accepted,NaN,NaN,1000
339917,9364510501,E6S06247081756,2018-07-25,847.0,8.0,EM,Accepted,NaN,NaN,1000
339918,9364779007,E6S01263690852,2018-06-26,5659.0,8.0,SC,Accepted,0.0,NaN,10000
339919,9364899410,M016K0654815D6,2018-07-06,6414.0,8.0,SO,Accepted,0.0,NaN,10000
339920,9365381207,G4K10362850201,2018-04-06,21572.0,8.0,EA,Accepted,0.0,NaN,100000
339921,9365381207,G4K10362850201,2018-06-07,21590.0,8.0,EA,Accepted,NaN,NaN,100000
339922,9365381207,G4K10362850201,2018-06-08,21602.0,8.0,EA,Accepted,NaN,NaN,100000
339923,9365381207,G4K10362850201,2018-06-16,21580.0,8.0,EA,Accepted,NaN,True,100000
339924,9365381207,G4K10362850201,2018-07-05,21549.0,NaN,EA,Accepted,NaN,True,100000
339925,9365381207,G4K10362850201,2018-07-29,21598.0,8.0,EA,Accepted,NaN,NaN,100000
339926,9365381207,G4K10362850201,2018-08-06,21575.0,8.0,EA,Accepted,NaN,True,100000
339927,9365848802,G4A00135409901,2018-02-07,15923.0,8.0,SW,Accepted,0.0,NaN,100000
339928,9365848802,G4A00135409901,2018-06-04,15748.0,8.0,SW,Accepted,NaN,True,100000
339929,9365848802,G4A00135409901,2018-06-08,15949.0,8.0,SW,Accepted,NaN,NaN,100000
339930,9365848802,G4A00135409901,2018-07-05,15828.0,8.0,SW,Accepted,NaN,True,100000
339931,9365848802,G4A00135409901,2018-07-06,15900.0,8.0,SW,Accepted,NaN,NaN,100000
339932,9366727402,G4K51501751601,2018-03-05,2009.0,8.0,EA,Accepted,0.0,NaN,10000
339933,9366727402,G4K51501751601,2018-05-07,2128.0,8.0,EA,Accepted,NaN,NaN,10000
339934,9366729002,G4W00525150701,2018-01-23,34967.0,NaN,WM,Accepted,0.0,NaN,100000
339935,9366729002,G4W00525150701,2018-06-02,35296.0,8.0,WM,Accepted,NaN,NaN,100000
339936,9366729002,G4W00525150701,2018-06-04,36236.0,8.0,WM,Accepted,NaN,NaN,100000
339937,9366729002,G4W00525150701,2018-06-07,36680.0,8.0,WM,Accepted,NaN,NaN,100000
339938,9366729002,G4W00525150701,2018-06-08,36712.0,8.0,WM,Accepted,NaN,NaN,100000
339939,9366729002,G4W00525150701,2018-07-03,35822.0,8.0,WM,Accepted,NaN,True,100000
339940,9366729002,G4W00525150701,2018-07-05,36496.0,8.0,WM,Accepted,NaN,NaN,100000
339941,9366729002,G4W00525150701,2018-08-06,36609.0,8.0,WM,Accepted,NaN,NaN,100000
339942,9367103907,G4W01732390902,2018-10-05,4551.0,8.0,EA,Accepted,0.0,NaN,10000
339943,9367526610,G4K64934450611,2018-02-07,20167.0,8.0,SC,Accepted,0.0,NaN,100000

In [107]:
correction_mask = (jDF['error']==True)
correction_mask

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27         True
28        False
29        False
          ...
339914    False
339915     True
339916    False
339917    False
339918    False
339919    False
339920    False
339921    False
339922    False
339923     True
339924     True
339925    False
339926     True
339927    False
339928     True
339929    False
339930     True
339931    False
339932    False
339933    False
339934    False
339935    False
339936    False
339937    False
339938    False
339939     True
339940    False
339941    False
339942    False
339943    False
Name: error, Length: 339944, dtype: bool

In [108]:
jDF.loc[correction_mask,'len'] = jDF.loc[correction_mask,'lenall']

In [109]:
jDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,mrmr,LDZ,STAT,len,error,lenall
0,11006910,G4K00362451701,2018-03-03,0.0,NaN,SW,Accepted,0.0,NaN,10
1,11006910,G4K00362451701,2018-06-18,996.0,8.0,SW,Accepted,NaN,NaN,1000
2,11006910,G4K01864940101,2016-12-28,49806.0,8.0,SW,Accepted,NaN,NaN,100000
3,11006910,G4K01864940101,2017-03-14,50806.0,NaN,SW,Accepted,NaN,NaN,100000
4,11006910,G4K01864940101,2017-09-20,51695.0,NaN,SW,Accepted,NaN,NaN,100000
5,11006910,G4K01864940101,2018-03-03,53973.0,NaN,SW,Accepted,NaN,NaN,100000
6,12807108,G4K68050890714,2016-04-29,11288.0,8.0,NW,Accepted,0.0,NaN,100000
7,12807108,G4K68050890714,2016-06-07,11557.0,NaN,NW,Accepted,NaN,NaN,100000
8,12807108,G4K68050890714,2016-12-16,12623.0,NaN,NW,Accepted,NaN,NaN,100000
9,12807108,G4K68050890714,2017-04-25,14901.0,8.0,NW,Accepted,NaN,NaN,100000
10,12807108,G4K68050890714,2017-06-22,15086.0,NaN,NW,Accepted,NaN,NaN,100000
11,12807108,G4K68050890714,2018-04-16,18810.0,NaN,NW,Accepted,NaN,NaN,100000
12,12992601,G4A00290751301,2016-08-20,3050.0,8.0,SE,Accepted,0.0,NaN,10000
13,12992601,G4A00290751301,2016-09-15,3064.0,8.0,SE,Accepted,NaN,NaN,10000
14,12992601,G4A00290751301,2016-10-16,3108.0,8.0,SE,Accepted,NaN,NaN,10000
15,12992601,G4A00290751301,2016-11-20,3203.0,8.0,SE,Accepted,NaN,NaN,10000
16,12992601,G4A00290751301,2016-12-22,3278.0,8.0,SE,Accepted,NaN,NaN,10000
17,12992601,G4A00290751301,2017-01-28,3420.0,8.0,SE,Accepted,NaN,NaN,10000
18,12992601,G4A00290751301,2017-03-22,3570.0,8.0,SE,Accepted,NaN,NaN,10000
19,12992601,G4A00290751301,2017-03-29,3584.0,NaN,SE,Accepted,NaN,NaN,10000
20,12992601,G4A00290751301,2017-04-14,3597.0,8.0,SE,Accepted,NaN,NaN,10000
21,12992601,G4A00290751301,2017-04-27,3622.0,8.0,SE,Accepted,NaN,NaN,10000
22,12992601,G4A00290751301,2017-07-20,3679.0,8.0,SE,Accepted,NaN,NaN,10000
23,12992601,G4A00290751301,2017-08-17,3696.0,8.0,SE,Accepted,NaN,NaN,10000
24,12992601,G4A00290751301,2017-09-27,3715.0,NaN,SE,Accepted,NaN,NaN,10000
25,12992601,G4A00290751301,2017-12-21,3987.0,8.0,SE,Accepted,NaN,NaN,10000
26,12992601,G4A00290751301,2018-02-19,4541.0,8.0,SE,Accepted,NaN,NaN,10000
27,12992601,G4A00290751301,2018-06-02,4398.0,8.0,SE,Accepted,10000.0,True,10000
28,12992601,G4A00290751301,2018-06-30,4966.0,8.0,SE,Accepted,NaN,NaN,10000
29,15821701,G4P01032961600,2016-02-12,1011.0,NaN,NW,Accepted,0.0,NaN,10000
...,...,...,...,...,...,...,...,...,...,...
339914,9364510501,E6S06247081756,2018-05-25,810.0,8.0,EM,Accepted,NaN,NaN,1000
339915,9364510501,E6S06247081756,2018-06-02,0.0,8.0,EM,Accepted,10.0,True,10
339916,9364510501,E6S06247081756,2018-06-25,831.0,8.0,EM,Accepted,NaN,NaN,1000
339917,9364510501,E6S06247081756,2018-07-25,847.0,8.0,EM,Accepted,NaN,NaN,1000
339918,9364779007,E6S01263690852,2018-06-26,5659.0,8.0,SC,Accepted,0.0,NaN,10000
339919,9364899410,M016K0654815D6,2018-07-06,6414.0,8.0,SO,Accepted,0.0,NaN,10000
339920,9365381207,G4K10362850201,2018-04-06,21572.0,8.0,EA,Accepted,0.0,NaN,100000
339921,9365381207,G4K10362850201,2018-06-07,21590.0,8.0,EA,Accepted,NaN,NaN,100000
339922,9365381207,G4K10362850201,2018-06-08,21602.0,8.0,EA,Accepted,NaN,NaN,100000
339923,9365381207,G4K10362850201,2018-06-16,21580.0,8.0,EA,Accepted,100000.0,True,100000
339924,9365381207,G4K10362850201,2018-07-05,21549.0,NaN,EA,Accepted,100000.0,True,100000
339925,9365381207,G4K10362850201,2018-07-29,21598.0,8.0,EA,Accepted,NaN,NaN,100000
339926,9365381207,G4K10362850201,2018-08-06,21575.0,8.0,EA,Accepted,100000.0,True,100000
339927,9365848802,G4A00135409901,2018-02-07,15923.0,8.0,SW,Accepted,0.0,NaN,100000
339928,9365848802,G4A00135409901,2018-06-04,15748.0,8.0,SW,Accepted,100000.0,True,100000
339929,9365848802,G4A00135409901,2018-06-08,15949.0,8.0,SW,Accepted,NaN,NaN,100000
339930,9365848802,G4A00135409901,2018-07-05,15828.0,8.0,SW,Accepted,100000.0,True,100000
339931,9365848802,G4A00135409901,2018-07-06,15900.0,8.0,SW,Accepted,NaN,NaN,100000
339932,9366727402,G4K51501751601,2018-03-05,2009.0,8.0,EA,Accepted,0.0,NaN,10000
339933,9366727402,G4K51501751601,2018-05-07,2128.0,8.0,EA,Accepted,NaN,NaN,10000
339934,9366729002,G4W00525150701,2018-01-23,34967.0,NaN,WM,Accepted,0.0,NaN,100000
339935,9366729002,G4W00525150701,2018-06-02,35296.0,8.0,WM,Accepted,NaN,NaN,100000
339936,9366729002,G4W00525150701,2018-06-04,36236.0,8.0,WM,Accepted,NaN,NaN,100000
339937,9366729002,G4W00525150701,2018-06-07,36680.0,8.0,WM,Accepted,NaN,NaN,100000
339938,9366729002,G4W00525150701,2018-06-08,36712.0,8.0,WM,Accepted,NaN,NaN,100000
339939,9366729002,G4W00525150701,2018-07-03,35822.0,8.0,WM,Accepted,100000.0,True,100000
339940,9366729002,G4W00525150701,2018-07-05,36496.0,8.0,WM,Accepted,NaN,NaN,100000
339941,9366729002,G4W00525150701,2018-08-06,36609.0,8.0,WM,Accepted,NaN,NaN,100000
339942,9367103907,G4W01732390902,2018-10-05,4551.0,8.0,EA,Accepted,0.0,NaN,10000
339943,9367526610,G4K64934450611,2018-02-07,20167.0,8.0,SC,Accepted,0.0,NaN,100000

In [110]:
for _, i in jDF.groupby(['meterPointIdentifier','SerialNum']):
    i = i.sort_values('eventDttm')
    i['len'] = i['len'].ffill()

In [111]:
jDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,mrmr,LDZ,STAT,len,error,lenall
0,11006910,G4K00362451701,2018-03-03,0.0,NaN,SW,Accepted,0.0,NaN,10
1,11006910,G4K00362451701,2018-06-18,996.0,8.0,SW,Accepted,NaN,NaN,1000
2,11006910,G4K01864940101,2016-12-28,49806.0,8.0,SW,Accepted,NaN,NaN,100000
3,11006910,G4K01864940101,2017-03-14,50806.0,NaN,SW,Accepted,NaN,NaN,100000
4,11006910,G4K01864940101,2017-09-20,51695.0,NaN,SW,Accepted,NaN,NaN,100000
5,11006910,G4K01864940101,2018-03-03,53973.0,NaN,SW,Accepted,NaN,NaN,100000
6,12807108,G4K68050890714,2016-04-29,11288.0,8.0,NW,Accepted,0.0,NaN,100000
7,12807108,G4K68050890714,2016-06-07,11557.0,NaN,NW,Accepted,NaN,NaN,100000
8,12807108,G4K68050890714,2016-12-16,12623.0,NaN,NW,Accepted,NaN,NaN,100000
9,12807108,G4K68050890714,2017-04-25,14901.0,8.0,NW,Accepted,NaN,NaN,100000
10,12807108,G4K68050890714,2017-06-22,15086.0,NaN,NW,Accepted,NaN,NaN,100000
11,12807108,G4K68050890714,2018-04-16,18810.0,NaN,NW,Accepted,NaN,NaN,100000
12,12992601,G4A00290751301,2016-08-20,3050.0,8.0,SE,Accepted,0.0,NaN,10000
13,12992601,G4A00290751301,2016-09-15,3064.0,8.0,SE,Accepted,NaN,NaN,10000
14,12992601,G4A00290751301,2016-10-16,3108.0,8.0,SE,Accepted,NaN,NaN,10000
15,12992601,G4A00290751301,2016-11-20,3203.0,8.0,SE,Accepted,NaN,NaN,10000
16,12992601,G4A00290751301,2016-12-22,3278.0,8.0,SE,Accepted,NaN,NaN,10000
17,12992601,G4A00290751301,2017-01-28,3420.0,8.0,SE,Accepted,NaN,NaN,10000
18,12992601,G4A00290751301,2017-03-22,3570.0,8.0,SE,Accepted,NaN,NaN,10000
19,12992601,G4A00290751301,2017-03-29,3584.0,NaN,SE,Accepted,NaN,NaN,10000
20,12992601,G4A00290751301,2017-04-14,3597.0,8.0,SE,Accepted,NaN,NaN,10000
21,12992601,G4A00290751301,2017-04-27,3622.0,8.0,SE,Accepted,NaN,NaN,10000
22,12992601,G4A00290751301,2017-07-20,3679.0,8.0,SE,Accepted,NaN,NaN,10000
23,12992601,G4A00290751301,2017-08-17,3696.0,8.0,SE,Accepted,NaN,NaN,10000
24,12992601,G4A00290751301,2017-09-27,3715.0,NaN,SE,Accepted,NaN,NaN,10000
25,12992601,G4A00290751301,2017-12-21,3987.0,8.0,SE,Accepted,NaN,NaN,10000
26,12992601,G4A00290751301,2018-02-19,4541.0,8.0,SE,Accepted,NaN,NaN,10000
27,12992601,G4A00290751301,2018-06-02,4398.0,8.0,SE,Accepted,10000.0,True,10000
28,12992601,G4A00290751301,2018-06-30,4966.0,8.0,SE,Accepted,NaN,NaN,10000
29,15821701,G4P01032961600,2016-02-12,1011.0,NaN,NW,Accepted,0.0,NaN,10000
...,...,...,...,...,...,...,...,...,...,...
339914,9364510501,E6S06247081756,2018-05-25,810.0,8.0,EM,Accepted,NaN,NaN,1000
339915,9364510501,E6S06247081756,2018-06-02,0.0,8.0,EM,Accepted,10.0,True,10
339916,9364510501,E6S06247081756,2018-06-25,831.0,8.0,EM,Accepted,NaN,NaN,1000
339917,9364510501,E6S06247081756,2018-07-25,847.0,8.0,EM,Accepted,NaN,NaN,1000
339918,9364779007,E6S01263690852,2018-06-26,5659.0,8.0,SC,Accepted,0.0,NaN,10000
339919,9364899410,M016K0654815D6,2018-07-06,6414.0,8.0,SO,Accepted,0.0,NaN,10000
339920,9365381207,G4K10362850201,2018-04-06,21572.0,8.0,EA,Accepted,0.0,NaN,100000
339921,9365381207,G4K10362850201,2018-06-07,21590.0,8.0,EA,Accepted,NaN,NaN,100000
339922,9365381207,G4K10362850201,2018-06-08,21602.0,8.0,EA,Accepted,NaN,NaN,100000
339923,9365381207,G4K10362850201,2018-06-16,21580.0,8.0,EA,Accepted,100000.0,True,100000
339924,9365381207,G4K10362850201,2018-07-05,21549.0,NaN,EA,Accepted,100000.0,True,100000
339925,9365381207,G4K10362850201,2018-07-29,21598.0,8.0,EA,Accepted,NaN,NaN,100000
339926,9365381207,G4K10362850201,2018-08-06,21575.0,8.0,EA,Accepted,100000.0,True,100000
339927,9365848802,G4A00135409901,2018-02-07,15923.0,8.0,SW,Accepted,0.0,NaN,100000
339928,9365848802,G4A00135409901,2018-06-04,15748.0,8.0,SW,Accepted,100000.0,True,100000
339929,9365848802,G4A00135409901,2018-06-08,15949.0,8.0,SW,Accepted,NaN,NaN,100000
339930,9365848802,G4A00135409901,2018-07-05,15828.0,8.0,SW,Accepted,100000.0,True,100000
339931,9365848802,G4A00135409901,2018-07-06,15900.0,8.0,SW,Accepted,NaN,NaN,100000
339932,9366727402,G4K51501751601,2018-03-05,2009.0,8.0,EA,Accepted,0.0,NaN,10000
339933,9366727402,G4K51501751601,2018-05-07,2128.0,8.0,EA,Accepted,NaN,NaN,10000
339934,9366729002,G4W00525150701,2018-01-23,34967.0,NaN,WM,Accepted,0.0,NaN,100000
339935,9366729002,G4W00525150701,2018-06-02,35296.0,8.0,WM,Accepted,NaN,NaN,100000
339936,9366729002,G4W00525150701,2018-06-04,36236.0,8.0,WM,Accepted,NaN,NaN,100000
339937,9366729002,G4W00525150701,2018-06-07,36680.0,8.0,WM,Accepted,NaN,NaN,100000
339938,9366729002,G4W00525150701,2018-06-08,36712.0,8.0,WM,Accepted,NaN,NaN,100000
339939,9366729002,G4W00525150701,2018-07-03,35822.0,8.0,WM,Accepted,100000.0,True,100000
339940,9366729002,G4W00525150701,2018-07-05,36496.0,8.0,WM,Accepted,NaN,NaN,100000
339941,9366729002,G4W00525150701,2018-08-06,36609.0,8.0,WM,Accepted,NaN,NaN,100000
339942,9367103907,G4W01732390902,2018-10-05,4551.0,8.0,EA,Accepted,0.0,NaN,10000
339943,9367526610,G4K64934450611,2018-02-07,20167.0,8.0,SC,Accepted,0.0,NaN,100000

In [112]:
jDF.loc[jDF['len']>0,'cumulative'] = jDF.loc[jDF['len']>0,'cumulative'] + jDF.loc[jDF['len']>0,'len']

In [113]:
from itertools import product

In [115]:
subtest = pd.DataFrame()

for _, i in jDF.groupby(['meterPointIdentifier','SerialNum']):
    
    i = i.sort_values('eventDttm')
    i['mrmr'] = i['mrmr'].ffill().bfill()
    
    
    
    
#     vals = i['cumulative'].unique()
    vals = i['cumulative']
    dates = i['eventDttm']
    val, val1 = zip(*product(vals, vals))
    vals_len = len(vals)
    date, date1 = zip(*product(dates,dates))

    def elongate(s, k):
        
        return pd.concat([s] * k, ignore_index=True)

    res = pd.DataFrame({'meterPointIdentifier': i['meterPointIdentifier'].pipe(elongate, vals_len),
                        'eventDttm': i['eventDttm'].pipe(elongate, vals_len),
                        'cumulative': i['cumulative'].pipe(elongate, vals_len),
                        'LDZ': i['LDZ'].pipe(elongate, vals_len),
                        'mrmr': i['mrmr'].pipe(elongate, vals_len),
                        'SerialNum': i['SerialNum'].pipe(elongate, vals_len),
                        'STAT': i['STAT'].pipe(elongate, vals_len),
                        'value': val,
                        'value1': val1,
                        'date':date,
                        'date1':date1
                       })


    subtest = subtest.append(res)

    
print(subtest)

    meterPointIdentifier  eventDttm  cumulative LDZ  mrmr       SerialNum  \
0               11006910 2018-03-03         0.0  SW   8.0  G4K00362451701
1               11006910 2018-06-18       996.0  SW   8.0  G4K00362451701
2               11006910 2018-03-03         0.0  SW   8.0  G4K00362451701
3               11006910 2018-06-18       996.0  SW   8.0  G4K00362451701
0               11006910 2016-12-28     49806.0  SW   8.0  G4K01864940101
1               11006910 2017-03-14     50806.0  SW   8.0  G4K01864940101
2               11006910 2017-09-20     51695.0  SW   8.0  G4K01864940101
3               11006910 2018-03-03     53973.0  SW   8.0  G4K01864940101
4               11006910 2016-12-28     49806.0  SW   8.0  G4K01864940101
5               11006910 2017-03-14     50806.0  SW   8.0  G4K01864940101
6               11006910 2017-09-20     51695.0  SW   8.0  G4K01864940101
7               11006910 2018-03-03     53973.0  SW   8.0  G4K01864940101
8               11006910 2016-12-28     49806.0  SW   8.0  G4K01864940101
9               11006910 2017-03-14     50806.0  SW   8.0  G4K01864940101
10              11006910 2017-09-20     51695.0  SW   8.0  G4K01864940101
11              11006910 2018-03-03     53973.0  SW   8.0  G4K01864940101
12              11006910 2016-12-28     49806.0  SW   8.0  G4K01864940101
13              11006910 2017-03-14     50806.0  SW   8.0  G4K01864940101
14              11006910 2017-09-20     51695.0  SW   8.0  G4K01864940101
15              11006910 2018-03-03     53973.0  SW   8.0  G4K01864940101
0               12807108 2016-04-29     11288.0  NW   8.0  G4K68050890714
1               12807108 2016-06-07     11557.0  NW   8.0  G4K68050890714
2               12807108 2016-12-16     12623.0  NW   8.0  G4K68050890714
3               12807108 2017-04-25     14901.0  NW   8.0  G4K68050890714
4               12807108 2017-06-22     15086.0  NW   8.0  G4K68050890714
5               12807108 2018-04-16     18810.0  NW   8.0  G4K68050890714
6               12807108 2016-04-29     11288.0  NW   8.0  G4K68050890714
7               12807108 2016-06-07     11557.0  NW   8.0  G4K68050890714
8               12807108 2016-12-16     12623.0  NW   8.0  G4K68050890714
9               12807108 2017-04-25     14901.0  NW   8.0  G4K68050890714
..                   ...        ...         ...  ..   ...             ...
36            9366729002 2018-06-08     36712.0  WM   8.0  G4W00525150701
37            9366729002 2018-07-03    135822.0  WM   8.0  G4W00525150701
38            9366729002 2018-07-05     36496.0  WM   8.0  G4W00525150701
39            9366729002 2018-08-06     36609.0  WM   8.0  G4W00525150701
40            9366729002 2018-01-23     34967.0  WM   8.0  G4W00525150701
41            9366729002 2018-06-02     35296.0  WM   8.0  G4W00525150701
42            9366729002 2018-06-04     36236.0  WM   8.0  G4W00525150701
43            9366729002 2018-06-07     36680.0  WM   8.0  G4W00525150701
44            9366729002 2018-06-08     36712.0  WM   8.0  G4W00525150701
45            9366729002 2018-07-03    135822.0  WM   8.0  G4W00525150701
46            9366729002 2018-07-05     36496.0  WM   8.0  G4W00525150701
47            9366729002 2018-08-06     36609.0  WM   8.0  G4W00525150701
48            9366729002 2018-01-23     34967.0  WM   8.0  G4W00525150701
49            9366729002 2018-06-02     35296.0  WM   8.0  G4W00525150701
50            9366729002 2018-06-04     36236.0  WM   8.0  G4W00525150701
51            9366729002 2018-06-07     36680.0  WM   8.0  G4W00525150701
52            9366729002 2018-06-08     36712.0  WM   8.0  G4W00525150701
53            9366729002 2018-07-03    135822.0  WM   8.0  G4W00525150701
54            9366729002 2018-07-05     36496.0  WM   8.0  G4W00525150701
55            9366729002 2018-08-06     36609.0  WM   8.0  G4W00525150701
56            9366729002 2018-01-23     34967.0  WM   8.0  G4W00525150701
57            9366729002 2018-06-02     35296.0  WM   8.0  G4W00525150701
58            9366729002 2018-06-04     36236.0  WM   8.0  G4W00525150701
59            9366729002 2018-06-07     36680.0  WM   8.0  G4W00525150701
60            9366729002 2018-06-08     36712.0  WM   8.0  G4W00525150701
61            9366729002 2018-07-03    135822.0  WM   8.0  G4W00525150701
62            9366729002 2018-07-05     36496.0  WM   8.0  G4W00525150701
63            9366729002 2018-08-06     36609.0  WM   8.0  G4W00525150701
0             9367103907 2018-10-05      4551.0  EA   8.0  G4W01732390902
0             9367526610 2018-02-07     20167.0  SC   8.0  G4K64934450611

        STAT     value    value1       date      date1
0   Accepted       0.0       0.0 2018-03-03 2018-03-03
1   Accepted       0.0     996.0 2018-03-03 2018-06-18
2   Accepted     996.0       0.0 2018-06-18 2018-03-03
3   Accepted     996.0     996.0 2018-06-18 2018-06-18
0   Accepted   49806.0   49806.0 2016-12-28 2016-12-28
1   Accepted   49806.0   50806.0 2016-12-28 2017-03-14
2   Accepted   49806.0   51695.0 2016-12-28 2017-09-20
3   Accepted   49806.0   53973.0 2016-12-28 2018-03-03
4   Accepted   50806.0   49806.0 2017-03-14 2016-12-28
5   Accepted   50806.0   50806.0 2017-03-14 2017-03-14
6   Accepted   50806.0   51695.0 2017-03-14 2017-09-20
7   Accepted   50806.0   53973.0 2017-03-14 2018-03-03
8   Accepted   51695.0   49806.0 2017-09-20 2016-12-28
9   Accepted   51695.0   50806.0 2017-09-20 2017-03-14
10  Accepted   51695.0   51695.0 2017-09-20 2017-09-20
11  Accepted   51695.0   53973.0 2017-09-20 2018-03-03
12  Accepted   53973.0   49806.0 2018-03-03 2016-12-28
13  Accepted   53973.0   50806.0 2018-03-03 2017-03-14
14  Accepted   53973.0   51695.0 2018-03-03 2017-09-20
15  Accepted   53973.0   53973.0 2018-03-03 2018-03-03
0   Accepted   11288.0   11288.0 2016-04-29 2016-04-29
1   Accepted   11288.0   11557.0 2016-04-29 2016-06-07
2   Accepted   11288.0   12623.0 2016-04-29 2016-12-16
3   Accepted   11288.0   14901.0 2016-04-29 2017-04-25
4   Accepted   11288.0   15086.0 2016-04-29 2017-06-22
5   Accepted   11288.0   18810.0 2016-04-29 2018-04-16
6   Accepted   11557.0   11288.0 2016-06-07 2016-04-29
7   Accepted   11557.0   11557.0 2016-06-07 2016-06-07
8   Accepted   11557.0   12623.0 2016-06-07 2016-12-16
9   Accepted   11557.0   14901.0 2016-06-07 2017-04-25
..       ...       ...       ...        ...        ...
36  Accepted   36712.0   36712.0 2018-06-08 2018-06-08
37  Accepted   36712.0  135822.0 2018-06-08 2018-07-03
38  Accepted   36712.0   36496.0 2018-06-08 2018-07-05
39  Accepted   36712.0   36609.0 2018-06-08 2018-08-06
40  Accepted  135822.0   34967.0 2018-07-03 2018-01-23
41  Accepted  135822.0   35296.0 2018-07-03 2018-06-02
42  Accepted  135822.0   36236.0 2018-07-03 2018-06-04
43  Accepted  135822.0   36680.0 2018-07-03 2018-06-07
44  Accepted  135822.0   36712.0 2018-07-03 2018-06-08
45  Accepted  135822.0  135822.0 2018-07-03 2018-07-03
46  Accepted  135822.0   36496.0 2018-07-03 2018-07-05
47  Accepted  135822.0   36609.0 2018-07-03 2018-08-06
48  Accepted   36496.0   34967.0 2018-07-05 2018-01-23
49  Accepted   36496.0   35296.0 2018-07-05 2018-06-02
50  Accepted   36496.0   36236.0 2018-07-05 2018-06-04
51  Accepted   36496.0   36680.0 2018-07-05 2018-06-07
52  Accepted   36496.0   36712.0 2018-07-05 2018-06-08
53  Accepted   36496.0  135822.0 2018-07-05 2018-07-03
54  Accepted   36496.0   36496.0 2018-07-05 2018-07-05
55  Accepted   36496.0   36609.0 2018-07-05 2018-08-06
56  Accepted   36609.0   34967.0 2018-08-06 2018-01-23
57  Accepted   36609.0   35296.0 2018-08-06 2018-06-02
58  Accepted   36609.0   36236.0 2018-08-06 2018-06-04
59  Accepted   36609.0   36680.0 2018-08-06 2018-06-07
60  Accepted   36609.0   36712.0 2018-08-06 2018-06-08
61  Accepted   36609.0  135822.0 2018-08-06 2018-07-03
62  Accepted   36609.0   36496.0 2018-08-06 2018-07-05
63  Accepted   36609.0   36609.0 2018-08-06 2018-08-06
0   Accepted    4551.0    4551.0 2018-10-05 2018-10-05
0   Accepted   20167.0   20167.0 2018-02-07 2018-02-07

[4282288 rows x 11 columns]

In [116]:
subtest.to_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/combination.csv')

In [117]:
subtest

,meterPointIdentifier,eventDttm,cumulative,LDZ,mrmr,SerialNum,STAT,value,value1,date,date1
0,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,0.0,0.0,2018-03-03,2018-03-03
1,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,0.0,996.0,2018-03-03,2018-06-18
2,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,996.0,0.0,2018-06-18,2018-03-03
3,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,996.0,996.0,2018-06-18,2018-06-18
0,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,49806.0,49806.0,2016-12-28,2016-12-28
1,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,49806.0,50806.0,2016-12-28,2017-03-14
2,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,49806.0,51695.0,2016-12-28,2017-09-20
3,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,49806.0,53973.0,2016-12-28,2018-03-03
4,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,50806.0,49806.0,2017-03-14,2016-12-28
5,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,50806.0,50806.0,2017-03-14,2017-03-14
6,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,50806.0,51695.0,2017-03-14,2017-09-20
7,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,50806.0,53973.0,2017-03-14,2018-03-03
8,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,51695.0,49806.0,2017-09-20,2016-12-28
9,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,51695.0,50806.0,2017-09-20,2017-03-14
10,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,51695.0,51695.0,2017-09-20,2017-09-20
11,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,51695.0,53973.0,2017-09-20,2018-03-03
12,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,53973.0,49806.0,2018-03-03,2016-12-28
13,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,53973.0,50806.0,2018-03-03,2017-03-14
14,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,53973.0,51695.0,2018-03-03,2017-09-20
15,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,53973.0,53973.0,2018-03-03,2018-03-03
0,12807108,2016-04-29,11288.0,NW,8.0,G4K68050890714,Accepted,11288.0,11288.0,2016-04-29,2016-04-29
1,12807108,2016-06-07,11557.0,NW,8.0,G4K68050890714,Accepted,11288.0,11557.0,2016-04-29,2016-06-07
2,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11288.0,12623.0,2016-04-29,2016-12-16
3,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11288.0,14901.0,2016-04-29,2017-04-25
4,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,11288.0,15086.0,2016-04-29,2017-06-22
5,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,11288.0,18810.0,2016-04-29,2018-04-16
6,12807108,2016-04-29,11288.0,NW,8.0,G4K68050890714,Accepted,11557.0,11288.0,2016-06-07,2016-04-29
7,12807108,2016-06-07,11557.0,NW,8.0,G4K68050890714,Accepted,11557.0,11557.0,2016-06-07,2016-06-07
8,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11557.0,12623.0,2016-06-07,2016-12-16
9,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11557.0,14901.0,2016-06-07,2017-04-25
...,...,...,...,...,...,...,...,...,...,...,...
36,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,36712.0,36712.0,2018-06-08,2018-06-08
37,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,36712.0,135822.0,2018-06-08,2018-07-03
38,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,36712.0,36496.0,2018-06-08,2018-07-05
39,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,36712.0,36609.0,2018-06-08,2018-08-06
40,9366729002,2018-01-23,34967.0,WM,8.0,G4W00525150701,Accepted,135822.0,34967.0,2018-07-03,2018-01-23
41,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,135822.0,35296.0,2018-07-03,2018-06-02
42,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,135822.0,36236.0,2018-07-03,2018-06-04
43,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,135822.0,36680.0,2018-07-03,2018-06-07
44,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,135822.0,36712.0,2018-07-03,2018-06-08
45,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,135822.0,135822.0,2018-07-03,2018-07-03
46,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,135822.0,36496.0,2018-07-03,2018-07-05
47,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,135822.0,36609.0,2018-07-03,2018-08-06
48,9366729002,2018-01-23,34967.0,WM,8.0,G4W00525150701,Accepted,36496.0,34967.0,2018-07-05,2018-01-23
49,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,36496.0,35296.0,2018-07-05,2018-06-02
50,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,36496.0,36236.0,2018-07-05,2018-06-04
51,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,36496.0,36680.0,2018-07-05,2018-06-07
52,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,36496.0,36712.0,2018-07-05,2018-06-08
53,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,36496.0,135822.0,2018-07-05,2018-07-03
54,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,36496.0,36496.0,2018-07-05,2018-07-05
55,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,36496.0,36609.0,2018-07-05,2018-08-06
56,9366729002,2018-01-23,34967.0,WM,8.0,G4W00525150701,Accepted,36609.0,34967.0,2018-08-06,2018-01-23
57,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,36609.0,35296.0,2018-08-06,2018-06-02
58,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,36609.0,36236.0,2018-08-06,2018-06-04
59,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,36609.0,36680.0,2018-08-06,2018-06-07
60,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,36609.0,36712.0,2018-08-06,2018-06-08
61,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,36609.0,135822.0,2018-08-06,2018-07-03
62,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,36609.0,36496.0,2018-08-06,2018-07-05
63,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,36609.0,36609.0,2018-08-06,2018-08-06
0,9367103907,2018-10-05,4551.0,EA,8.0,G4W01732390902,Accepted,4551.0,4551.0,2018-10-05,2018-10-05
0,9367526610,2018-02-07,20167.0,SC,8.0,G4K64934450611,Accepted,20167.0,20167.0,2018-02-07,2018-02-07

In [121]:
# subtest = pd.read_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/combination.csv')

In [118]:

test = subtest[:10].drop_duplicates(subset=['meterPointIdentifier','SerialNum','value','value1','date','date1'], keep='first', inplace=False)

test

,meterPointIdentifier,eventDttm,cumulative,LDZ,mrmr,SerialNum,STAT,value,value1,date,date1
0,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,0.0,0.0,2018-03-03,2018-03-03
1,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,0.0,996.0,2018-03-03,2018-06-18
2,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,996.0,0.0,2018-06-18,2018-03-03
3,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,996.0,996.0,2018-06-18,2018-06-18
0,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,49806.0,49806.0,2016-12-28,2016-12-28
1,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,49806.0,50806.0,2016-12-28,2017-03-14
2,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,49806.0,51695.0,2016-12-28,2017-09-20
3,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,49806.0,53973.0,2016-12-28,2018-03-03
4,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,50806.0,49806.0,2017-03-14,2016-12-28
5,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,50806.0,50806.0,2017-03-14,2017-03-14

In [119]:
jDF1 = subtest.drop_duplicates(subset=['meterPointIdentifier','SerialNum','value','value1','date','date1'], keep='first', inplace=False)

In [120]:
jDF1

,meterPointIdentifier,eventDttm,cumulative,LDZ,mrmr,SerialNum,STAT,value,value1,date,date1
0,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,0.0,0.0,2018-03-03,2018-03-03
1,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,0.0,996.0,2018-03-03,2018-06-18
2,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,996.0,0.0,2018-06-18,2018-03-03
3,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,996.0,996.0,2018-06-18,2018-06-18
0,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,49806.0,49806.0,2016-12-28,2016-12-28
1,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,49806.0,50806.0,2016-12-28,2017-03-14
2,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,49806.0,51695.0,2016-12-28,2017-09-20
3,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,49806.0,53973.0,2016-12-28,2018-03-03
4,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,50806.0,49806.0,2017-03-14,2016-12-28
5,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,50806.0,50806.0,2017-03-14,2017-03-14
6,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,50806.0,51695.0,2017-03-14,2017-09-20
7,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,50806.0,53973.0,2017-03-14,2018-03-03
8,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,51695.0,49806.0,2017-09-20,2016-12-28
9,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,51695.0,50806.0,2017-09-20,2017-03-14
10,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,51695.0,51695.0,2017-09-20,2017-09-20
11,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,51695.0,53973.0,2017-09-20,2018-03-03
12,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,53973.0,49806.0,2018-03-03,2016-12-28
13,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,53973.0,50806.0,2018-03-03,2017-03-14
14,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,53973.0,51695.0,2018-03-03,2017-09-20
15,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,53973.0,53973.0,2018-03-03,2018-03-03
0,12807108,2016-04-29,11288.0,NW,8.0,G4K68050890714,Accepted,11288.0,11288.0,2016-04-29,2016-04-29
1,12807108,2016-06-07,11557.0,NW,8.0,G4K68050890714,Accepted,11288.0,11557.0,2016-04-29,2016-06-07
2,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11288.0,12623.0,2016-04-29,2016-12-16
3,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11288.0,14901.0,2016-04-29,2017-04-25
4,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,11288.0,15086.0,2016-04-29,2017-06-22
5,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,11288.0,18810.0,2016-04-29,2018-04-16
6,12807108,2016-04-29,11288.0,NW,8.0,G4K68050890714,Accepted,11557.0,11288.0,2016-06-07,2016-04-29
7,12807108,2016-06-07,11557.0,NW,8.0,G4K68050890714,Accepted,11557.0,11557.0,2016-06-07,2016-06-07
8,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11557.0,12623.0,2016-06-07,2016-12-16
9,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11557.0,14901.0,2016-06-07,2017-04-25
...,...,...,...,...,...,...,...,...,...,...,...
36,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,36712.0,36712.0,2018-06-08,2018-06-08
37,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,36712.0,135822.0,2018-06-08,2018-07-03
38,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,36712.0,36496.0,2018-06-08,2018-07-05
39,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,36712.0,36609.0,2018-06-08,2018-08-06
40,9366729002,2018-01-23,34967.0,WM,8.0,G4W00525150701,Accepted,135822.0,34967.0,2018-07-03,2018-01-23
41,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,135822.0,35296.0,2018-07-03,2018-06-02
42,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,135822.0,36236.0,2018-07-03,2018-06-04
43,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,135822.0,36680.0,2018-07-03,2018-06-07
44,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,135822.0,36712.0,2018-07-03,2018-06-08
45,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,135822.0,135822.0,2018-07-03,2018-07-03
46,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,135822.0,36496.0,2018-07-03,2018-07-05
47,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,135822.0,36609.0,2018-07-03,2018-08-06
48,9366729002,2018-01-23,34967.0,WM,8.0,G4W00525150701,Accepted,36496.0,34967.0,2018-07-05,2018-01-23
49,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,36496.0,35296.0,2018-07-05,2018-06-02
50,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,36496.0,36236.0,2018-07-05,2018-06-04
51,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,36496.0,36680.0,2018-07-05,2018-06-07
52,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,36496.0,36712.0,2018-07-05,2018-06-08
53,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,36496.0,135822.0,2018-07-05,2018-07-03
54,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,36496.0,36496.0,2018-07-05,2018-07-05
55,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,36496.0,36609.0,2018-07-05,2018-08-06
56,9366729002,2018-01-23,34967.0,WM,8.0,G4W00525150701,Accepted,36609.0,34967.0,2018-08-06,2018-01-23
57,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,36609.0,35296.0,2018-08-06,2018-06-02
58,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,36609.0,36236.0,2018-08-06,2018-06-04
59,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,36609.0,36680.0,2018-08-06,2018-06-07
60,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,36609.0,36712.0,2018-08-06,2018-06-08
61,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,36609.0,135822.0,2018-08-06,2018-07-03
62,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,36609.0,36496.0,2018-08-06,2018-07-05
63,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,36609.0,36609.0,2018-08-06,2018-08-06
0,9367103907,2018-10-05,4551.0,EA,8.0,G4W01732390902,Accepted,4551.0,4551.0,2018-10-05,2018-10-05
0,9367526610,2018-02-07,20167.0,SC,8.0,G4K64934450611,Accepted,20167.0,20167.0,2018-02-07,2018-02-07

In [122]:
ldzAlp['validDt'] = pd.to_datetime(ldzAlp['validDt'])
jDF1['eventDttm'] = pd.to_datetime(jDF1['eventDttm'])
jDF1['date'] = pd.to_datetime(jDF1['date'])
jDF1['date1'] = pd.to_datetime(jDF1['date1'])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [123]:
jDF1['Delta_Date'] = jDF1['date1'] - jDF1['date']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [225]:
jDF1[jDF1['meterPointIdentifier']==11006910]

,meterPointIdentifier,eventDttm,cumulative,LDZ,mrmr,SerialNum,STAT,value,value1,date,date1,Delta_Date
0,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,0.0,0.0,2018-03-03,2018-03-03,0
1,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,0.0,996.0,2018-03-03,2018-06-18,107
2,11006910,2018-03-03,0.0,SW,8.0,G4K00362451701,Accepted,996.0,0.0,2018-06-18,2018-03-03,-107
3,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,996.0,996.0,2018-06-18,2018-06-18,0
0,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,49806.0,49806.0,2016-12-28,2016-12-28,0
1,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,49806.0,50806.0,2016-12-28,2017-03-14,76
2,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266
3,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430
4,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,50806.0,49806.0,2017-03-14,2016-12-28,-76
5,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,50806.0,50806.0,2017-03-14,2017-03-14,0
6,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190
7,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354
8,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,51695.0,49806.0,2017-09-20,2016-12-28,-266
9,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,51695.0,50806.0,2017-09-20,2017-03-14,-190
10,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,51695.0,51695.0,2017-09-20,2017-09-20,0
11,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164
12,11006910,2016-12-28,49806.0,SW,8.0,G4K01864940101,Accepted,53973.0,49806.0,2018-03-03,2016-12-28,-430
13,11006910,2017-03-14,50806.0,SW,8.0,G4K01864940101,Accepted,53973.0,50806.0,2018-03-03,2017-03-14,-354
14,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,53973.0,51695.0,2018-03-03,2017-09-20,-164
15,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,53973.0,53973.0,2018-03-03,2018-03-03,0

In [126]:
jDF1['Delta_Date'] = jDF1['Delta_Date'].dt.days
jDF1.dtypes

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

meterPointIdentifier             int64
eventDttm               datetime64[ns]
cumulative                     float64
LDZ                             object
mrmr                           float64
SerialNum                       object
STAT                            object
value                          float64
value1                         float64
date                    datetime64[ns]
date1                   datetime64[ns]
Delta_Date                       int64
dtype: object

In [127]:
mask = (jDF1['Delta_Date']>=90)

newjDF = jDF1.loc[mask]
newjDF

,meterPointIdentifier,eventDttm,cumulative,LDZ,mrmr,SerialNum,STAT,value,value1,date,date1,Delta_Date
1,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,0.0,996.0,2018-03-03,2018-06-18,107
2,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266
3,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430
6,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190
7,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354
11,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164
2,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11288.0,12623.0,2016-04-29,2016-12-16,231
3,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11288.0,14901.0,2016-04-29,2017-04-25,361
4,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,11288.0,15086.0,2016-04-29,2017-06-22,419
5,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,11288.0,18810.0,2016-04-29,2018-04-16,717
8,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11557.0,12623.0,2016-06-07,2016-12-16,192
9,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11557.0,14901.0,2016-06-07,2017-04-25,322
10,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,11557.0,15086.0,2016-06-07,2017-06-22,380
11,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,11557.0,18810.0,2016-06-07,2018-04-16,678
15,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,12623.0,14901.0,2016-12-16,2017-04-25,130
16,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,12623.0,15086.0,2016-12-16,2017-06-22,188
17,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,12623.0,18810.0,2016-12-16,2018-04-16,486
23,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,14901.0,18810.0,2017-04-25,2018-04-16,356
29,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,15086.0,18810.0,2017-06-22,2018-04-16,298
3,12992601,2016-11-20,3203.0,SE,8.0,G4A00290751301,Accepted,3050.0,3203.0,2016-08-20,2016-11-20,92
4,12992601,2016-12-22,3278.0,SE,8.0,G4A00290751301,Accepted,3050.0,3278.0,2016-08-20,2016-12-22,124
5,12992601,2017-01-28,3420.0,SE,8.0,G4A00290751301,Accepted,3050.0,3420.0,2016-08-20,2017-01-28,161
6,12992601,2017-03-22,3570.0,SE,8.0,G4A00290751301,Accepted,3050.0,3570.0,2016-08-20,2017-03-22,214
7,12992601,2017-03-29,3584.0,SE,8.0,G4A00290751301,Accepted,3050.0,3584.0,2016-08-20,2017-03-29,221
8,12992601,2017-04-14,3597.0,SE,8.0,G4A00290751301,Accepted,3050.0,3597.0,2016-08-20,2017-04-14,237
9,12992601,2017-04-27,3622.0,SE,8.0,G4A00290751301,Accepted,3050.0,3622.0,2016-08-20,2017-04-27,250
10,12992601,2017-07-20,3679.0,SE,8.0,G4A00290751301,Accepted,3050.0,3679.0,2016-08-20,2017-07-20,334
11,12992601,2017-08-17,3696.0,SE,8.0,G4A00290751301,Accepted,3050.0,3696.0,2016-08-20,2017-08-17,362
12,12992601,2017-09-27,3715.0,SE,8.0,G4A00290751301,Accepted,3050.0,3715.0,2016-08-20,2017-09-27,403
13,12992601,2017-12-21,3987.0,SE,8.0,G4A00290751301,Accepted,3050.0,3987.0,2016-08-20,2017-12-21,488
...,...,...,...,...,...,...,...,...,...,...,...,...
36,9362748704,2018-04-13,7368.0,SO,8.0,G4A01767191201,Accepted,6432.0,7368.0,2018-01-13,2018-04-13,90
37,9362748704,2018-05-13,7423.0,SO,8.0,G4A01767191201,Accepted,6432.0,7423.0,2018-01-13,2018-05-13,120
38,9362748704,2018-06-16,7442.0,SO,8.0,G4A01767191201,Accepted,6432.0,7442.0,2018-01-13,2018-06-16,154
39,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,6432.0,7449.0,2018-01-13,2018-07-13,181
48,9362748704,2018-06-16,7442.0,SO,8.0,G4A01767191201,Accepted,6797.0,7442.0,2018-02-13,2018-06-16,123
49,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,6797.0,7449.0,2018-02-13,2018-07-13,150
58,9362748704,2018-06-16,7442.0,SO,8.0,G4A01767191201,Accepted,7125.0,7442.0,2018-03-13,2018-06-16,95
59,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,7125.0,7449.0,2018-03-13,2018-07-13,122
69,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,7368.0,7449.0,2018-04-13,2018-07-13,91
1,9363117808,2018-12-04,1882.0,NW,8.0,G4K00293191701,Accepted,979.0,1882.0,2018-06-15,2018-12-04,172
4,9364510501,2018-06-02,10.0,EM,8.0,E6S06247081756,Accepted,183.0,10.0,2018-02-25,2018-06-02,97
5,9364510501,2018-06-25,831.0,EM,8.0,E6S06247081756,Accepted,183.0,831.0,2018-02-25,2018-06-25,120
6,9364510501,2018-07-25,847.0,EM,8.0,E6S06247081756,Accepted,183.0,847.0,2018-02-25,2018-07-25,150
12,9364510501,2018-06-25,831.0,EM,8.0,E6S06247081756,Accepted,519.0,831.0,2018-03-25,2018-06-25,92
13,9364510501,2018-07-25,847.0,EM,8.0,E6S06247081756,Accepted,519.0,847.0,2018-03-25,2018-07-25,122
20,9364510501,2018-07-25,847.0,EM,8.0,E6S06247081756,Accepted,730.0,847.0,2018-04-25,2018-07-25,91
4,9365381207,2018-07-05,121549.0,EA,8.0,G4K10362850201,Accepted,21572.0,121549.0,2018-04-06,2018-07-05,90
5,9365381207,2018-07-29,21598.0,EA,8.0,G4K10362850201,Accepted,21572.0,21598.0,2018-04-06,2018-07-29,114
6,9365381207,2018-08-06,121575.0,EA,8.0,G4K10362850201,Accepted,21572.0,121575.0,2018-04-06,2018-08-06,122
1,9365848802,2018-06-04,115748.0,SW,8.0,G4A00135409901,Accepted,15923.0,115748.0,2018-02-07,2018-06-04,117
2,9365848802,2018-06-08,15949.0,SW,8.0,G4A00135409901,Accepted,15923.0,15949.0,2018-02-07,2018-06-08,121
3,9365848802,2018-07-05,115828.0,SW,8.0,G4A00135409901,Accepted,15923.0,115828.0,2018-02-07,2018-07-05,148
4,9365848802,2018-07-06,15900.0,SW,8.0,G4A00135409901,Accepted,15923.0,15900.0,2018-02-07,2018-07-06,149
1,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,34967.0,35296.0,2018-01-23,2018-06-02,130
2,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,34967.0,36236.0,2018-01-23,2018-06-04,132
3,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,34967.0,36680.0,2018-01-23,2018-06-07,135
4,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,34967.0,36712.0,2018-01-23,2018-06-08,136
5,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,34967.0,135822.0,2018-01-23,2018-07-03,161
6,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,34967.0,36496.0,2018-01-23,2018-07-05,163
7,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,34967.0,36609.0,2018-01-23,2018-08-06,195

In [128]:
len(newjDF)

1481933

In [129]:
newjDF['deltaR'] = np.nan

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [130]:
newjDF['deltaR'] = newjDF['value1'] - newjDF['value']
newjDF

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,meterPointIdentifier,eventDttm,cumulative,LDZ,mrmr,SerialNum,STAT,value,value1,date,date1,Delta_Date,deltaR
1,11006910,2018-06-18,996.0,SW,8.0,G4K00362451701,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0
2,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0
3,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0
6,11006910,2017-09-20,51695.0,SW,8.0,G4K01864940101,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0
7,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0
11,11006910,2018-03-03,53973.0,SW,8.0,G4K01864940101,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0
2,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11288.0,12623.0,2016-04-29,2016-12-16,231,1335.0
3,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11288.0,14901.0,2016-04-29,2017-04-25,361,3613.0
4,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,11288.0,15086.0,2016-04-29,2017-06-22,419,3798.0
5,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,11288.0,18810.0,2016-04-29,2018-04-16,717,7522.0
8,12807108,2016-12-16,12623.0,NW,8.0,G4K68050890714,Accepted,11557.0,12623.0,2016-06-07,2016-12-16,192,1066.0
9,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,11557.0,14901.0,2016-06-07,2017-04-25,322,3344.0
10,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,11557.0,15086.0,2016-06-07,2017-06-22,380,3529.0
11,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,11557.0,18810.0,2016-06-07,2018-04-16,678,7253.0
15,12807108,2017-04-25,14901.0,NW,8.0,G4K68050890714,Accepted,12623.0,14901.0,2016-12-16,2017-04-25,130,2278.0
16,12807108,2017-06-22,15086.0,NW,8.0,G4K68050890714,Accepted,12623.0,15086.0,2016-12-16,2017-06-22,188,2463.0
17,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,12623.0,18810.0,2016-12-16,2018-04-16,486,6187.0
23,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,14901.0,18810.0,2017-04-25,2018-04-16,356,3909.0
29,12807108,2018-04-16,18810.0,NW,8.0,G4K68050890714,Accepted,15086.0,18810.0,2017-06-22,2018-04-16,298,3724.0
3,12992601,2016-11-20,3203.0,SE,8.0,G4A00290751301,Accepted,3050.0,3203.0,2016-08-20,2016-11-20,92,153.0
4,12992601,2016-12-22,3278.0,SE,8.0,G4A00290751301,Accepted,3050.0,3278.0,2016-08-20,2016-12-22,124,228.0
5,12992601,2017-01-28,3420.0,SE,8.0,G4A00290751301,Accepted,3050.0,3420.0,2016-08-20,2017-01-28,161,370.0
6,12992601,2017-03-22,3570.0,SE,8.0,G4A00290751301,Accepted,3050.0,3570.0,2016-08-20,2017-03-22,214,520.0
7,12992601,2017-03-29,3584.0,SE,8.0,G4A00290751301,Accepted,3050.0,3584.0,2016-08-20,2017-03-29,221,534.0
8,12992601,2017-04-14,3597.0,SE,8.0,G4A00290751301,Accepted,3050.0,3597.0,2016-08-20,2017-04-14,237,547.0
9,12992601,2017-04-27,3622.0,SE,8.0,G4A00290751301,Accepted,3050.0,3622.0,2016-08-20,2017-04-27,250,572.0
10,12992601,2017-07-20,3679.0,SE,8.0,G4A00290751301,Accepted,3050.0,3679.0,2016-08-20,2017-07-20,334,629.0
11,12992601,2017-08-17,3696.0,SE,8.0,G4A00290751301,Accepted,3050.0,3696.0,2016-08-20,2017-08-17,362,646.0
12,12992601,2017-09-27,3715.0,SE,8.0,G4A00290751301,Accepted,3050.0,3715.0,2016-08-20,2017-09-27,403,665.0
13,12992601,2017-12-21,3987.0,SE,8.0,G4A00290751301,Accepted,3050.0,3987.0,2016-08-20,2017-12-21,488,937.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,9362748704,2018-04-13,7368.0,SO,8.0,G4A01767191201,Accepted,6432.0,7368.0,2018-01-13,2018-04-13,90,936.0
37,9362748704,2018-05-13,7423.0,SO,8.0,G4A01767191201,Accepted,6432.0,7423.0,2018-01-13,2018-05-13,120,991.0
38,9362748704,2018-06-16,7442.0,SO,8.0,G4A01767191201,Accepted,6432.0,7442.0,2018-01-13,2018-06-16,154,1010.0
39,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,6432.0,7449.0,2018-01-13,2018-07-13,181,1017.0
48,9362748704,2018-06-16,7442.0,SO,8.0,G4A01767191201,Accepted,6797.0,7442.0,2018-02-13,2018-06-16,123,645.0
49,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,6797.0,7449.0,2018-02-13,2018-07-13,150,652.0
58,9362748704,2018-06-16,7442.0,SO,8.0,G4A01767191201,Accepted,7125.0,7442.0,2018-03-13,2018-06-16,95,317.0
59,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,7125.0,7449.0,2018-03-13,2018-07-13,122,324.0
69,9362748704,2018-07-13,7449.0,SO,8.0,G4A01767191201,Accepted,7368.0,7449.0,2018-04-13,2018-07-13,91,81.0
1,9363117808,2018-12-04,1882.0,NW,8.0,G4K00293191701,Accepted,979.0,1882.0,2018-06-15,2018-12-04,172,903.0
4,9364510501,2018-06-02,10.0,EM,8.0,E6S06247081756,Accepted,183.0,10.0,2018-02-25,2018-06-02,97,-173.0
5,9364510501,2018-06-25,831.0,EM,8.0,E6S06247081756,Accepted,183.0,831.0,2018-02-25,2018-06-25,120,648.0
6,9364510501,2018-07-25,847.0,EM,8.0,E6S06247081756,Accepted,183.0,847.0,2018-02-25,2018-07-25,150,664.0
12,9364510501,2018-06-25,831.0,EM,8.0,E6S06247081756,Accepted,519.0,831.0,2018-03-25,2018-06-25,92,312.0
13,9364510501,2018-07-25,847.0,EM,8.0,E6S06247081756,Accepted,519.0,847.0,2018-03-25,2018-07-25,122,328.0
20,9364510501,2018-07-25,847.0,EM,8.0,E6S06247081756,Accepted,730.0,847.0,2018-04-25,2018-07-25,91,117.0
4,9365381207,2018-07-05,121549.0,EA,8.0,G4K10362850201,Accepted,21572.0,121549.0,2018-04-06,2018-07-05,90,99977.0
5,9365381207,2018-07-29,21598.0,EA,8.0,G4K10362850201,Accepted,21572.0,21598.0,2018-04-06,2018-07-29,114,26.0
6,9365381207,2018-08-06,121575.0,EA,8.0,G4K10362850201,Accepted,21572.0,121575.0,2018-04-06,2018-08-06,122,100003.0
1,9365848802,2018-06-04,115748.0,SW,8.0,G4A00135409901,Accepted,15923.0,115748.0,2018-02-07,2018-06-04,117,99825.0
2,9365848802,2018-06-08,15949.0,SW,8.0,G4A00135409901,Accepted,15923.0,15949.0,2018-02-07,2018-06-08,121,26.0
3,9365848802,2018-07-05,115828.0,SW,8.0,G4A00135409901,Accepted,15923.0,115828.0,2018-02-07,2018-07-05,148,99905.0
4,9365848802,2018-07-06,15900.0,SW,8.0,G4A00135409901,Accepted,15923.0,15900.0,2018-02-07,2018-07-06,149,-23.0
1,9366729002,2018-06-02,35296.0,WM,8.0,G4W00525150701,Accepted,34967.0,35296.0,2018-01-23,2018-06-02,130,329.0
2,9366729002,2018-06-04,36236.0,WM,8.0,G4W00525150701,Accepted,34967.0,36236.0,2018-01-23,2018-06-04,132,1269.0
3,9366729002,2018-06-07,36680.0,WM,8.0,G4W00525150701,Accepted,34967.0,36680.0,2018-01-23,2018-06-07,135,1713.0
4,9366729002,2018-06-08,36712.0,WM,8.0,G4W00525150701,Accepted,34967.0,36712.0,2018-01-23,2018-06-08,136,1745.0
5,9366729002,2018-07-03,135822.0,WM,8.0,G4W00525150701,Accepted,34967.0,135822.0,2018-01-23,2018-07-03,161,100855.0
6,9366729002,2018-07-05,36496.0,WM,8.0,G4W00525150701,Accepted,34967.0,36496.0,2018-01-23,2018-07-05,163,1529.0
7,9366729002,2018-08-06,36609.0,WM,8.0,G4W00525150701,Accepted,34967.0,36609.0,2018-01-23,2018-08-06,195,1642.0

In [135]:
mrmr = newjDF.mrmr
newjDF = newjDF.drop('mrmr', axis=1)
def alpcalc(row):
    r1 = row.date
    r2 = row.date1
    ldz = row.LDZ
    dayDiff = row.Delta_Date
    
    total_ALP = ldzAlp.loc[(dayDiff>=90) & (r1 <= ldzAlp.validDt) & (r2>= ldzAlp.validDt) & (ldz == ldzAlp.code), 'ALP'].sum()

    return total_ALP

newjDF['ALP'] = newjDF.apply(alpcalc, axis=1)
newjDF['mrmr'] = mrmr

In [136]:
newjDF.to_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/finalUsage_Alp.csv')

In [ ]:
# newjDF = pd.read_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/finalUsage_Alp.csv')

In [229]:
newjDF[newjDF['meterPointIdentifier']==11006910]

,meterPointIdentifier,SerialNum,eventDttm,cumulative,LDZ,STAT,value,value1,date,date1,Delta_Date,deltaR,ALP,mrmr,UnitConvUsage,AQ
0,11006910,G4K00362451701,2018-06-18,996.0,SW,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0,100.020326,8.0,11147.457760,40679.952217
1,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0,265.584589,8.0,21142.116173,29056.175407
2,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0,512.599098,8.0,46638.008520,33208.940820
3,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0,184.321343,8.0,9949.889507,19703.142408
4,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0,431.335852,8.0,35445.781853,29994.516608
5,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0,248.061622,8.0,25495.892347,37514.874859

In [144]:
newjDF = newjDF.groupby(['meterPointIdentifier','SerialNum']).ffill().groupby(['meterPointIdentifier','SerialNum']).bfill()

In [145]:
newjDF.dropna(axis=0, subset=['mrmr'], inplace=True)

In [149]:
newjDF[newjDF['ALP'].isnull()]

Empty DataFrame
Columns: [meterPointIdentifier, SerialNum, eventDttm, cumulative, LDZ, STAT, value, value1, date, date1, Delta_Date, deltaR, ALP, mrmr]
Index: []

In [163]:
#------------------conversion for cubic metres constants
volCorrectiontemppres = 1.02264
calorificVal = 39.4
convfrmJules = 3.6
mcubekwh = volCorrectiontemppres*calorificVal/convfrmJules
print(mcubekwh)
#---------------------conversion for 100s of Cubic feet constants
convtoCubicM = 2.83
mcubeftkwh = convtoCubicM*volCorrectiontemppres*calorificVal/convfrmJules
print(mcubeftkwh)

11.192226666666665
31.674001466666663

In [156]:
mask1 = (newjDF['mrmr']==8.0) & (newjDF['ALP']!=0)
newjDF.loc[mask1,'UnitConvUsage'] = newjDF.loc[mask1,'deltaR'] * mcubekwh

In [162]:
newjDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,LDZ,STAT,value,value1,date,date1,Delta_Date,deltaR,ALP,mrmr,UnitConvUsage
1,11006910,G4K00362451701,2018-06-18,996.0,SW,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0,100.020326,8.0,1.114746e+04
2,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0,265.584589,8.0,2.114212e+04
3,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0,512.599098,8.0,4.663801e+04
6,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0,184.321343,8.0,9.949890e+03
7,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0,431.335852,8.0,3.544578e+04
11,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0,248.061622,8.0,2.549589e+04
2,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11288.0,12623.0,2016-04-29,2016-12-16,231,1335.0,144.465738,8.0,1.494162e+04
3,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11288.0,14901.0,2016-04-29,2017-04-25,361,3613.0,277.441902,8.0,4.043751e+04
4,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11288.0,15086.0,2016-04-29,2017-06-22,419,3798.0,334.045794,8.0,4.250808e+04
5,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11288.0,18810.0,2016-04-29,2018-04-16,717,7522.0,721.921049,8.0,8.418793e+04
8,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11557.0,12623.0,2016-06-07,2016-12-16,192,1066.0,120.327752,8.0,1.193091e+04
9,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11557.0,14901.0,2016-06-07,2017-04-25,322,3344.0,253.303916,8.0,3.742681e+04
10,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11557.0,15086.0,2016-06-07,2017-06-22,380,3529.0,309.907808,8.0,3.949737e+04
11,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11557.0,18810.0,2016-06-07,2018-04-16,678,7253.0,697.783063,8.0,8.117722e+04
15,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,12623.0,14901.0,2016-12-16,2017-04-25,130,2278.0,134.049380,8.0,2.549589e+04
16,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,12623.0,15086.0,2016-12-16,2017-06-22,188,2463.0,190.653272,8.0,2.756645e+04
17,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,12623.0,18810.0,2016-12-16,2018-04-16,486,6187.0,578.528527,8.0,6.924631e+04
23,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,14901.0,18810.0,2017-04-25,2018-04-16,356,3909.0,445.606712,8.0,4.375041e+04
29,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,15086.0,18810.0,2017-06-22,2018-04-16,298,3724.0,388.938305,8.0,4.167985e+04
3,12992601,G4A00290751301,2016-11-20,3203.0,SE,Accepted,3050.0,3203.0,2016-08-20,2016-11-20,92,153.0,65.883813,8.0,1.712411e+03
4,12992601,G4A00290751301,2016-12-22,3278.0,SE,Accepted,3050.0,3278.0,2016-08-20,2016-12-22,124,228.0,100.186073,8.0,2.551828e+03
5,12992601,G4A00290751301,2017-01-28,3420.0,SE,Accepted,3050.0,3420.0,2016-08-20,2017-01-28,161,370.0,136.300758,8.0,4.141124e+03
6,12992601,G4A00290751301,2017-03-22,3570.0,SE,Accepted,3050.0,3570.0,2016-08-20,2017-03-22,214,520.0,194.783360,8.0,5.819958e+03
7,12992601,G4A00290751301,2017-03-29,3584.0,SE,Accepted,3050.0,3584.0,2016-08-20,2017-03-29,221,534.0,202.238818,8.0,5.976649e+03
8,12992601,G4A00290751301,2017-04-14,3597.0,SE,Accepted,3050.0,3597.0,2016-08-20,2017-04-14,237,547.0,218.824498,8.0,6.122148e+03
9,12992601,G4A00290751301,2017-04-27,3622.0,SE,Accepted,3050.0,3622.0,2016-08-20,2017-04-27,250,572.0,231.515579,8.0,6.401954e+03
10,12992601,G4A00290751301,2017-07-20,3679.0,SE,Accepted,3050.0,3679.0,2016-08-20,2017-07-20,334,629.0,312.310815,8.0,7.039911e+03
11,12992601,G4A00290751301,2017-08-17,3696.0,SE,Accepted,3050.0,3696.0,2016-08-20,2017-08-17,362,646.0,337.439620,8.0,7.230178e+03
12,12992601,G4A00290751301,2017-09-27,3715.0,SE,Accepted,3050.0,3715.0,2016-08-20,2017-09-27,403,665.0,375.982460,8.0,7.442831e+03
13,12992601,G4A00290751301,2017-12-21,3987.0,SE,Accepted,3050.0,3987.0,2016-08-20,2017-12-21,488,937.0,482.653488,8.0,1.048712e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,9362748704,G4A01767191201,2018-04-13,7368.0,SO,Accepted,6432.0,7368.0,2018-01-13,2018-04-13,90,936.0,146.295937,8.0,1.047592e+04
37,9362748704,G4A01767191201,2018-05-13,7423.0,SO,Accepted,6432.0,7423.0,2018-01-13,2018-05-13,120,991.0,171.746999,8.0,1.109150e+04
38,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6432.0,7442.0,2018-01-13,2018-06-16,154,1010.0,187.925246,8.0,1.130415e+04
39,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6432.0,7449.0,2018-01-13,2018-07-13,181,1017.0,196.619388,8.0,1.138249e+04
48,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6797.0,7442.0,2018-02-13,2018-06-16,123,645.0,131.028240,8.0,7.218986e+03
49,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6797.0,7449.0,2018-02-13,2018-07-13,150,652.0,139.722382,8.0,7.297332e+03
58,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,7125.0,7442.0,2018-03-13,2018-06-16,95,317.0,83.878605,8.0,3.547936e+03
59,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7125.0,7449.0,2018-03-13,2018-07-13,122,324.0,92.572747,8.0,3.626281e+03
69,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7368.0,7449.0,2018-04-13,2018-07-13,91,81.0,51.432541,8.0,9.065704e+02
1,9363117808,G4K00293191701,2018-12-04,1882.0,NW,Accepted,979.0,1882.0,2018-06-15,2018-12-04,172,903.0,33.787339,8.0,1.010658e+04
4,9364510501,E6S06247081756,2018-06-02,10.0,EM,Accepted,183.0,10.0,2018-02-25,2018-06-02,97,-173.0,105.420002,8.0,-1.936255e+03
5,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,183.0,831.0,2018-02-25,2018-06-25,120,648.0,112.937353,8.0,7.252563e+03
6,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,183.0,847.0,2018-02-25,2018-07-25,150,664.0,120.311636,8.0,7.431639e+03
12,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,519.0,831.0,2018-03-25,2018-06-25,92,312.0,69.061888,8.0,3.491975e+03
13,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,519.0,847.0,2018-03-25,2018-07-25,122,328.0,76.436171,8.0,3.671050e+03
20,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,730.0,847.0,2018-04-25,2018-07-25,91,117.0,40.385999,8.0,1.309491e+03
4,9365381207,G4K10362850201,2018-07-05,121549.0,EA,Accepted,21572.0,121549.0,2018-04-06,2018-07-05,90,99977.0,57.433733,8.0,1.118965e+06
5,9365381207,G4K10362850201,2018-07-29,21598.0,EA,Accepted,21572.0,21598.0,2018-04-06,2018-07-29,114,26.0,64.325320,8.0,2.909979e+02
6,9365381207,G4K10362850201,2018-08-06,121575.0,EA,Accepted,21572.0,121575.0,2018-04-06,2018-08-06,122,100003.0,66.477169,8.0,1.119256e+06
1,9365848802,G4A00135409901,2018-06-04,115748.0,SW,Accepted,15923.0,115748.0,2018-02-07,2018-06-04,117,99825.0,138.723412,8.0,1.117264e+06
2,9365848802,G4A00135409901,2018-06-08,15949.0,SW,Accepted,15923.0,15949.0,2018-02-07,2018-06-08,121,26.0,140.214048,8.0,2.909979e+02
3,9365848802,G4A00135409901,2018-07-05,115828.0,SW,Accepted,15923.0,115828.0,2018-02-07,2018-07-05,148,99905.0,148.447060,8.0,1.118159e+06
4,9365848802,G4A00135409901,2018-07-06,15900.0,SW,Accepted,15923.0,15900.0,2018-02-07,2018-07-06,149,-23.0,148.716117,8.0,-2.574212e+02
1,9366729002,G4W00525150701,2018-06-02,35296.0,WM,Accepted,34967.0,35296.0,2018-01-23,2018-06-02,130,329.0,163.717307,8.0,3.682243e+03
2,9366729002,G4W00525150701,2018-06-04,36236.0,WM,Accepted,34967.0,36236.0,2018-01-23,2018-06-04,132,1269.0,164.501997,8.0,1.420294e+04
3,9366729002,G4W00525150701,2018-06-07,36680.0,WM,Accepted,34967.0,36680.0,2018-01-23,2018-06-07,135,1713.0,165.635765,8.0,1.917228e+04
4,9366729002,G4W00525150701,2018-06-08,36712.0,WM,Accepted,34967.0,36712.0,2018-01-23,2018-06-08,136,1745.0,166.011859,8.0,1.953044e+04
5,9366729002,G4W00525150701,2018-07-03,135822.0,WM,Accepted,34967.0,135822.0,2018-01-23,2018-07-03,161,100855.0,173.364350,8.0,1.128792e+06
6,9366729002,G4W00525150701,2018-07-05,36496.0,WM,Accepted,34967.0,36496.0,2018-01-23,2018-07-05,163,1529.0,173.856314,8.0,1.711291e+04
7,9366729002,G4W00525150701,2018-08-06,36609.0,WM,Accepted,34967.0,36609.0,2018-01-23,2018-08-06,195,1642.0,181.167647,8.0,1.837764e+04

In [166]:
mask2 = (newjDF['mrmr']==14.0) & (newjDF['ALP']!=0)
newjDF.loc[mask2,'UnitConvUsage']=newjDF.loc[mask2,'deltaR'] * mcubeftkwh

In [172]:
newjDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,LDZ,STAT,value,value1,date,date1,Delta_Date,deltaR,ALP,mrmr,UnitConvUsage
1,11006910,G4K00362451701,2018-06-18,996.0,SW,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0,100.020326,8.0,1.114746e+04
2,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0,265.584589,8.0,2.114212e+04
3,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0,512.599098,8.0,4.663801e+04
6,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0,184.321343,8.0,9.949890e+03
7,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0,431.335852,8.0,3.544578e+04
11,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0,248.061622,8.0,2.549589e+04
2,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11288.0,12623.0,2016-04-29,2016-12-16,231,1335.0,144.465738,8.0,1.494162e+04
3,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11288.0,14901.0,2016-04-29,2017-04-25,361,3613.0,277.441902,8.0,4.043751e+04
4,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11288.0,15086.0,2016-04-29,2017-06-22,419,3798.0,334.045794,8.0,4.250808e+04
5,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11288.0,18810.0,2016-04-29,2018-04-16,717,7522.0,721.921049,8.0,8.418793e+04
8,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11557.0,12623.0,2016-06-07,2016-12-16,192,1066.0,120.327752,8.0,1.193091e+04
9,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11557.0,14901.0,2016-06-07,2017-04-25,322,3344.0,253.303916,8.0,3.742681e+04
10,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11557.0,15086.0,2016-06-07,2017-06-22,380,3529.0,309.907808,8.0,3.949737e+04
11,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11557.0,18810.0,2016-06-07,2018-04-16,678,7253.0,697.783063,8.0,8.117722e+04
15,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,12623.0,14901.0,2016-12-16,2017-04-25,130,2278.0,134.049380,8.0,2.549589e+04
16,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,12623.0,15086.0,2016-12-16,2017-06-22,188,2463.0,190.653272,8.0,2.756645e+04
17,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,12623.0,18810.0,2016-12-16,2018-04-16,486,6187.0,578.528527,8.0,6.924631e+04
23,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,14901.0,18810.0,2017-04-25,2018-04-16,356,3909.0,445.606712,8.0,4.375041e+04
29,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,15086.0,18810.0,2017-06-22,2018-04-16,298,3724.0,388.938305,8.0,4.167985e+04
3,12992601,G4A00290751301,2016-11-20,3203.0,SE,Accepted,3050.0,3203.0,2016-08-20,2016-11-20,92,153.0,65.883813,8.0,1.712411e+03
4,12992601,G4A00290751301,2016-12-22,3278.0,SE,Accepted,3050.0,3278.0,2016-08-20,2016-12-22,124,228.0,100.186073,8.0,2.551828e+03
5,12992601,G4A00290751301,2017-01-28,3420.0,SE,Accepted,3050.0,3420.0,2016-08-20,2017-01-28,161,370.0,136.300758,8.0,4.141124e+03
6,12992601,G4A00290751301,2017-03-22,3570.0,SE,Accepted,3050.0,3570.0,2016-08-20,2017-03-22,214,520.0,194.783360,8.0,5.819958e+03
7,12992601,G4A00290751301,2017-03-29,3584.0,SE,Accepted,3050.0,3584.0,2016-08-20,2017-03-29,221,534.0,202.238818,8.0,5.976649e+03
8,12992601,G4A00290751301,2017-04-14,3597.0,SE,Accepted,3050.0,3597.0,2016-08-20,2017-04-14,237,547.0,218.824498,8.0,6.122148e+03
9,12992601,G4A00290751301,2017-04-27,3622.0,SE,Accepted,3050.0,3622.0,2016-08-20,2017-04-27,250,572.0,231.515579,8.0,6.401954e+03
10,12992601,G4A00290751301,2017-07-20,3679.0,SE,Accepted,3050.0,3679.0,2016-08-20,2017-07-20,334,629.0,312.310815,8.0,7.039911e+03
11,12992601,G4A00290751301,2017-08-17,3696.0,SE,Accepted,3050.0,3696.0,2016-08-20,2017-08-17,362,646.0,337.439620,8.0,7.230178e+03
12,12992601,G4A00290751301,2017-09-27,3715.0,SE,Accepted,3050.0,3715.0,2016-08-20,2017-09-27,403,665.0,375.982460,8.0,7.442831e+03
13,12992601,G4A00290751301,2017-12-21,3987.0,SE,Accepted,3050.0,3987.0,2016-08-20,2017-12-21,488,937.0,482.653488,8.0,1.048712e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,9362748704,G4A01767191201,2018-04-13,7368.0,SO,Accepted,6432.0,7368.0,2018-01-13,2018-04-13,90,936.0,146.295937,8.0,1.047592e+04
37,9362748704,G4A01767191201,2018-05-13,7423.0,SO,Accepted,6432.0,7423.0,2018-01-13,2018-05-13,120,991.0,171.746999,8.0,1.109150e+04
38,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6432.0,7442.0,2018-01-13,2018-06-16,154,1010.0,187.925246,8.0,1.130415e+04
39,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6432.0,7449.0,2018-01-13,2018-07-13,181,1017.0,196.619388,8.0,1.138249e+04
48,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6797.0,7442.0,2018-02-13,2018-06-16,123,645.0,131.028240,8.0,7.218986e+03
49,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6797.0,7449.0,2018-02-13,2018-07-13,150,652.0,139.722382,8.0,7.297332e+03
58,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,7125.0,7442.0,2018-03-13,2018-06-16,95,317.0,83.878605,8.0,3.547936e+03
59,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7125.0,7449.0,2018-03-13,2018-07-13,122,324.0,92.572747,8.0,3.626281e+03
69,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7368.0,7449.0,2018-04-13,2018-07-13,91,81.0,51.432541,8.0,9.065704e+02
1,9363117808,G4K00293191701,2018-12-04,1882.0,NW,Accepted,979.0,1882.0,2018-06-15,2018-12-04,172,903.0,33.787339,8.0,1.010658e+04
4,9364510501,E6S06247081756,2018-06-02,10.0,EM,Accepted,183.0,10.0,2018-02-25,2018-06-02,97,-173.0,105.420002,8.0,-1.936255e+03
5,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,183.0,831.0,2018-02-25,2018-06-25,120,648.0,112.937353,8.0,7.252563e+03
6,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,183.0,847.0,2018-02-25,2018-07-25,150,664.0,120.311636,8.0,7.431639e+03
12,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,519.0,831.0,2018-03-25,2018-06-25,92,312.0,69.061888,8.0,3.491975e+03
13,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,519.0,847.0,2018-03-25,2018-07-25,122,328.0,76.436171,8.0,3.671050e+03
20,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,730.0,847.0,2018-04-25,2018-07-25,91,117.0,40.385999,8.0,1.309491e+03
4,9365381207,G4K10362850201,2018-07-05,121549.0,EA,Accepted,21572.0,121549.0,2018-04-06,2018-07-05,90,99977.0,57.433733,8.0,1.118965e+06
5,9365381207,G4K10362850201,2018-07-29,21598.0,EA,Accepted,21572.0,21598.0,2018-04-06,2018-07-29,114,26.0,64.325320,8.0,2.909979e+02
6,9365381207,G4K10362850201,2018-08-06,121575.0,EA,Accepted,21572.0,121575.0,2018-04-06,2018-08-06,122,100003.0,66.477169,8.0,1.119256e+06
1,9365848802,G4A00135409901,2018-06-04,115748.0,SW,Accepted,15923.0,115748.0,2018-02-07,2018-06-04,117,99825.0,138.723412,8.0,1.117264e+06
2,9365848802,G4A00135409901,2018-06-08,15949.0,SW,Accepted,15923.0,15949.0,2018-02-07,2018-06-08,121,26.0,140.214048,8.0,2.909979e+02
3,9365848802,G4A00135409901,2018-07-05,115828.0,SW,Accepted,15923.0,115828.0,2018-02-07,2018-07-05,148,99905.0,148.447060,8.0,1.118159e+06
4,9365848802,G4A00135409901,2018-07-06,15900.0,SW,Accepted,15923.0,15900.0,2018-02-07,2018-07-06,149,-23.0,148.716117,8.0,-2.574212e+02
1,9366729002,G4W00525150701,2018-06-02,35296.0,WM,Accepted,34967.0,35296.0,2018-01-23,2018-06-02,130,329.0,163.717307,8.0,3.682243e+03
2,9366729002,G4W00525150701,2018-06-04,36236.0,WM,Accepted,34967.0,36236.0,2018-01-23,2018-06-04,132,1269.0,164.501997,8.0,1.420294e+04
3,9366729002,G4W00525150701,2018-06-07,36680.0,WM,Accepted,34967.0,36680.0,2018-01-23,2018-06-07,135,1713.0,165.635765,8.0,1.917228e+04
4,9366729002,G4W00525150701,2018-06-08,36712.0,WM,Accepted,34967.0,36712.0,2018-01-23,2018-06-08,136,1745.0,166.011859,8.0,1.953044e+04
5,9366729002,G4W00525150701,2018-07-03,135822.0,WM,Accepted,34967.0,135822.0,2018-01-23,2018-07-03,161,100855.0,173.364350,8.0,1.128792e+06
6,9366729002,G4W00525150701,2018-07-05,36496.0,WM,Accepted,34967.0,36496.0,2018-01-23,2018-07-05,163,1529.0,173.856314,8.0,1.711291e+04
7,9366729002,G4W00525150701,2018-08-06,36609.0,WM,Accepted,34967.0,36609.0,2018-01-23,2018-08-06,195,1642.0,181.167647,8.0,1.837764e+04

In [178]:
AQMask = (newjDF['ALP']!=0) & (newjDF.UnitConvUsage.notnull())
newjDF.loc[AQMask,'AQ']=(newjDF.loc[AQMask,'UnitConvUsage']*365)/newjDF.loc[AQMask,'ALP']
newjDF

,meterPointIdentifier,SerialNum,eventDttm,cumulative,LDZ,STAT,value,value1,date,date1,Delta_Date,deltaR,ALP,mrmr,UnitConvUsage,AQ
1,11006910,G4K00362451701,2018-06-18,996.0,SW,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0,100.020326,8.0,1.114746e+04,4.067995e+04
2,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0,265.584589,8.0,2.114212e+04,2.905618e+04
3,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0,512.599098,8.0,4.663801e+04,3.320894e+04
6,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0,184.321343,8.0,9.949890e+03,1.970314e+04
7,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0,431.335852,8.0,3.544578e+04,2.999452e+04
11,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0,248.061622,8.0,2.549589e+04,3.751487e+04
2,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11288.0,12623.0,2016-04-29,2016-12-16,231,1335.0,144.465738,8.0,1.494162e+04,3.775077e+04
3,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11288.0,14901.0,2016-04-29,2017-04-25,361,3613.0,277.441902,8.0,4.043751e+04,5.319922e+04
4,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11288.0,15086.0,2016-04-29,2017-06-22,419,3798.0,334.045794,8.0,4.250808e+04,4.644707e+04
5,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11288.0,18810.0,2016-04-29,2018-04-16,717,7522.0,721.921049,8.0,8.418793e+04,4.256503e+04
8,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11557.0,12623.0,2016-06-07,2016-12-16,192,1066.0,120.327752,8.0,1.193091e+04,3.619101e+04
9,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11557.0,14901.0,2016-06-07,2017-04-25,322,3344.0,253.303916,8.0,3.742681e+04,5.393041e+04
10,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11557.0,15086.0,2016-06-07,2017-06-22,380,3529.0,309.907808,8.0,3.949737e+04,4.651880e+04
11,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11557.0,18810.0,2016-06-07,2018-04-16,678,7253.0,697.783063,8.0,8.117722e+04,4.246260e+04
15,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,12623.0,14901.0,2016-12-16,2017-04-25,130,2278.0,134.049380,8.0,2.549589e+04,6.942218e+04
16,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,12623.0,15086.0,2016-12-16,2017-06-22,188,2463.0,190.653272,8.0,2.756645e+04,5.277515e+04
17,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,12623.0,18810.0,2016-12-16,2018-04-16,486,6187.0,578.528527,8.0,6.924631e+04,4.368826e+04
23,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,14901.0,18810.0,2017-04-25,2018-04-16,356,3909.0,445.606712,8.0,4.375041e+04,3.583631e+04
29,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,15086.0,18810.0,2017-06-22,2018-04-16,298,3724.0,388.938305,8.0,4.167985e+04,3.911455e+04
3,12992601,G4A00290751301,2016-11-20,3203.0,SE,Accepted,3050.0,3203.0,2016-08-20,2016-11-20,92,153.0,65.883813,8.0,1.712411e+03,9.486851e+03
4,12992601,G4A00290751301,2016-12-22,3278.0,SE,Accepted,3050.0,3278.0,2016-08-20,2016-12-22,124,228.0,100.186073,8.0,2.551828e+03,9.296872e+03
5,12992601,G4A00290751301,2017-01-28,3420.0,SE,Accepted,3050.0,3420.0,2016-08-20,2017-01-28,161,370.0,136.300758,8.0,4.141124e+03,1.108952e+04
6,12992601,G4A00290751301,2017-03-22,3570.0,SE,Accepted,3050.0,3570.0,2016-08-20,2017-03-22,214,520.0,194.783360,8.0,5.819958e+03,1.090588e+04
7,12992601,G4A00290751301,2017-03-29,3584.0,SE,Accepted,3050.0,3584.0,2016-08-20,2017-03-29,221,534.0,202.238818,8.0,5.976649e+03,1.078664e+04
8,12992601,G4A00290751301,2017-04-14,3597.0,SE,Accepted,3050.0,3597.0,2016-08-20,2017-04-14,237,547.0,218.824498,8.0,6.122148e+03,1.021176e+04
9,12992601,G4A00290751301,2017-04-27,3622.0,SE,Accepted,3050.0,3622.0,2016-08-20,2017-04-27,250,572.0,231.515579,8.0,6.401954e+03,1.009311e+04
10,12992601,G4A00290751301,2017-07-20,3679.0,SE,Accepted,3050.0,3679.0,2016-08-20,2017-07-20,334,629.0,312.310815,8.0,7.039911e+03,8.227596e+03
11,12992601,G4A00290751301,2017-08-17,3696.0,SE,Accepted,3050.0,3696.0,2016-08-20,2017-08-17,362,646.0,337.439620,8.0,7.230178e+03,7.820703e+03
12,12992601,G4A00290751301,2017-09-27,3715.0,SE,Accepted,3050.0,3715.0,2016-08-20,2017-09-27,403,665.0,375.982460,8.0,7.442831e+03,7.225425e+03
13,12992601,G4A00290751301,2017-12-21,3987.0,SE,Accepted,3050.0,3987.0,2016-08-20,2017-12-21,488,937.0,482.653488,8.0,1.048712e+04,7.930736e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,9362748704,G4A01767191201,2018-04-13,7368.0,SO,Accepted,6432.0,7368.0,2018-01-13,2018-04-13,90,936.0,146.295937,8.0,1.047592e+04,2.613683e+04
37,9362748704,G4A01767191201,2018-05-13,7423.0,SO,Accepted,6432.0,7423.0,2018-01-13,2018-05-13,120,991.0,171.746999,8.0,1.109150e+04,2.357186e+04
38,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6432.0,7442.0,2018-01-13,2018-06-16,154,1010.0,187.925246,8.0,1.130415e+04,2.195562e+04
39,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6432.0,7449.0,2018-01-13,2018-07-13,181,1017.0,196.619388,8.0,1.138249e+04,2.113022e+04
48,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6797.0,7442.0,2018-02-13,2018-06-16,123,645.0,131.028240,8.0,7.218986e+03,2.010963e+04
49,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6797.0,7449.0,2018-02-13,2018-07-13,150,652.0,139.722382,8.0,7.297332e+03,1.906299e+04
58,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,7125.0,7442.0,2018-03-13,2018-06-16,95,317.0,83.878605,8.0,3.547936e+03,1.543894e+04
59,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7125.0,7449.0,2018-03-13,2018-07-13,122,324.0,92.572747,8.0,3.626281e+03,1.429787e+04
69,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7368.0,7449.0,2018-04-13,2018-07-13,91,81.0,51.432541,8.0,9.065704e+02,6.433635e+03
1,9363117808,G4K00293191701,2018-12-04,1882.0,NW,Accepted,979.0,1882.0,2018-06-15,2018-12-04,172,903.0,33.787339,8.0,1.010658e+04,1.091800e+05
4,9364510501,E6S06247081756,2018-06-02,10.0,EM,Accepted,183.0,10.0,2018-02-25,2018-06-02,97,-173.0,105.420002,8.0,-1.936255e+03,-6.703976e+03
5,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,183.0,831.0,2018-02-25,2018-06-25,120,648.0,112.937353,8.0,7.252563e+03,2.343941e+04
6,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,183.0,847.0,2018-02-25,2018-07-25,150,664.0,120.311636,8.0,7.431639e+03,2.254602e+04
12,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,519.0,831.0,2018-03-25,2018-06-25,92,312.0,69.061888,8.0,3.491975e+03,1.845549e+04
13,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,519.0,847.0,2018-03-25,2018-07-25,122,328.0,76.436171,8.0,3.671050e+03,1.753010e+04
20,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,730.0,847.0,2018-04-25,2018-07-25,91,117.0,40.385999,8.0,1.309491e+03,1.183489e+04
4,9365381207,G4K10362850201,2018-07-05,121549.0,EA,Accepted,21572.0,121549.0,2018-04-06,2018-07-05,90,99977.0,57.433733,8.0,1.118965e+06,7.111192e+06
5,9365381207,G4K10362850201,2018-07-29,21598.0,EA,Accepted,21572.0,21598.0,2018-04-06,2018-07-29,114,26.0,64.325320,8.0,2.909979e+02,1.651204e+03
6,9365381207,G4K10362850201,2018-08-06,121575.0,EA,Accepted,21572.0,121575.0,2018-04-06,2018-08-06,122,100003.0,66.477169,8.0,1.119256e+06,6.145396e+06
1,9365848802,G4A00135409901,2018-06-04,115748.0,SW,Accepted,15923.0,115748.0,2018-02-07,2018-06-04,117,99825.0,138.723412,8.0,1.117264e+06,2.939672e+06
2,9365848802,G4A00135409901,2018-06-08,15949.0,SW,Accepted,15923.0,15949.0,2018-02-07,2018-06-08,121,26.0,140.214048,8.0,2.909979e+02,7.575149e+02
3,9365848802,G4A00135409901,2018-07-05,115828.0,SW,Accepted,15923.0,115828.0,2018-02-07,2018-07-05,148,99905.0,148.447060,8.0,1.118159e+06,2.749318e+06
4,9365848802,G4A00135409901,2018-07-06,15900.0,SW,Accepted,15923.0,15900.0,2018-02-07,2018-07-06,149,-23.0,148.716117,8.0,-2.574212e+02,-6.317993e+02
1,9366729002,G4W00525150701,2018-06-02,35296.0,WM,Accepted,34967.0,35296.0,2018-01-23,2018-06-02,130,329.0,163.717307,8.0,3.682243e+03,8.209386e+03
2,9366729002,G4W00525150701,2018-06-04,36236.0,WM,Accepted,34967.0,36236.0,2018-01-23,2018-06-04,132,1269.0,164.501997,8.0,1.420294e+04,3.151373e+04
3,9366729002,G4W00525150701,2018-06-07,36680.0,WM,Accepted,34967.0,36680.0,2018-01-23,2018-06-07,135,1713.0,165.635765,8.0,1.917228e+04,4.224863e+04
4,9366729002,G4W00525150701,2018-06-08,36712.0,WM,Accepted,34967.0,36712.0,2018-01-23,2018-06-08,136,1745.0,166.011859,8.0,1.953044e+04,4.294036e+04
5,9366729002,G4W00525150701,2018-07-03,135822.0,WM,Accepted,34967.0,135822.0,2018-01-23,2018-07-03,161,100855.0,173.364350,8.0,1.128792e+06,2.376550e+06
6,9366729002,G4W00525150701,2018-07-05,36496.0,WM,Accepted,34967.0,36496.0,2018-01-23,2018-07-05,163,1529.0,173.856314,8.0,1.711291e+04,3.592745e+04
7,9366729002,G4W00525150701,2018-08-06,36609.0,WM,Accepted,34967.0,36609.0,2018-01-23,2018-08-06,195,1642.0,181.167647,8.0,1.837764e+04,3.702558e+04

In [180]:
newjDF.reset_index(drop = True, inplace = True)

In [227]:
newjDF[newjDF['meterPointIdentifier']==11006910]

,meterPointIdentifier,SerialNum,eventDttm,cumulative,LDZ,STAT,value,value1,date,date1,Delta_Date,deltaR,ALP,mrmr,UnitConvUsage,AQ
0,11006910,G4K00362451701,2018-06-18,996.0,SW,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0,100.020326,8.0,11147.457760,40679.952217
1,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0,265.584589,8.0,21142.116173,29056.175407
2,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0,512.599098,8.0,46638.008520,33208.940820
3,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0,184.321343,8.0,9949.889507,19703.142408
4,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0,431.335852,8.0,35445.781853,29994.516608
5,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0,248.061622,8.0,25495.892347,37514.874859

In [188]:
mask = ((newjDF['deltaR']>0) & (newjDF.ALP!=0) & (newjDF.mrmr.notnull()))

In [189]:
newjDF1 = newjDF[((newjDF['deltaR']>0) & (newjDF.ALP!=0) & (newjDF.mrmr.notnull()))]
newjDF1 = newjDF1.drop_duplicates(subset=['meterPointIdentifier','SerialNum','value','value1','date','date1','AQ'], keep='first', inplace=False)
newjDF1

,meterPointIdentifier,SerialNum,eventDttm,cumulative,LDZ,STAT,value,value1,date,date1,Delta_Date,deltaR,ALP,mrmr,UnitConvUsage,AQ
0,11006910,G4K00362451701,2018-06-18,996.0,SW,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0,100.020326,8.0,1.114746e+04,4.067995e+04
1,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0,265.584589,8.0,2.114212e+04,2.905618e+04
2,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0,512.599098,8.0,4.663801e+04,3.320894e+04
3,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0,184.321343,8.0,9.949890e+03,1.970314e+04
4,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0,431.335852,8.0,3.544578e+04,2.999452e+04
5,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0,248.061622,8.0,2.549589e+04,3.751487e+04
6,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11288.0,12623.0,2016-04-29,2016-12-16,231,1335.0,144.465738,8.0,1.494162e+04,3.775077e+04
7,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11288.0,14901.0,2016-04-29,2017-04-25,361,3613.0,277.441902,8.0,4.043751e+04,5.319922e+04
8,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11288.0,15086.0,2016-04-29,2017-06-22,419,3798.0,334.045794,8.0,4.250808e+04,4.644707e+04
9,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11288.0,18810.0,2016-04-29,2018-04-16,717,7522.0,721.921049,8.0,8.418793e+04,4.256503e+04
10,12807108,G4K68050890714,2016-12-16,12623.0,NW,Accepted,11557.0,12623.0,2016-06-07,2016-12-16,192,1066.0,120.327752,8.0,1.193091e+04,3.619101e+04
11,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,11557.0,14901.0,2016-06-07,2017-04-25,322,3344.0,253.303916,8.0,3.742681e+04,5.393041e+04
12,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,11557.0,15086.0,2016-06-07,2017-06-22,380,3529.0,309.907808,8.0,3.949737e+04,4.651880e+04
13,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,11557.0,18810.0,2016-06-07,2018-04-16,678,7253.0,697.783063,8.0,8.117722e+04,4.246260e+04
14,12807108,G4K68050890714,2017-04-25,14901.0,NW,Accepted,12623.0,14901.0,2016-12-16,2017-04-25,130,2278.0,134.049380,8.0,2.549589e+04,6.942218e+04
15,12807108,G4K68050890714,2017-06-22,15086.0,NW,Accepted,12623.0,15086.0,2016-12-16,2017-06-22,188,2463.0,190.653272,8.0,2.756645e+04,5.277515e+04
16,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,12623.0,18810.0,2016-12-16,2018-04-16,486,6187.0,578.528527,8.0,6.924631e+04,4.368826e+04
17,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,14901.0,18810.0,2017-04-25,2018-04-16,356,3909.0,445.606712,8.0,4.375041e+04,3.583631e+04
18,12807108,G4K68050890714,2018-04-16,18810.0,NW,Accepted,15086.0,18810.0,2017-06-22,2018-04-16,298,3724.0,388.938305,8.0,4.167985e+04,3.911455e+04
19,12992601,G4A00290751301,2016-11-20,3203.0,SE,Accepted,3050.0,3203.0,2016-08-20,2016-11-20,92,153.0,65.883813,8.0,1.712411e+03,9.486851e+03
20,12992601,G4A00290751301,2016-12-22,3278.0,SE,Accepted,3050.0,3278.0,2016-08-20,2016-12-22,124,228.0,100.186073,8.0,2.551828e+03,9.296872e+03
21,12992601,G4A00290751301,2017-01-28,3420.0,SE,Accepted,3050.0,3420.0,2016-08-20,2017-01-28,161,370.0,136.300758,8.0,4.141124e+03,1.108952e+04
22,12992601,G4A00290751301,2017-03-22,3570.0,SE,Accepted,3050.0,3570.0,2016-08-20,2017-03-22,214,520.0,194.783360,8.0,5.819958e+03,1.090588e+04
23,12992601,G4A00290751301,2017-03-29,3584.0,SE,Accepted,3050.0,3584.0,2016-08-20,2017-03-29,221,534.0,202.238818,8.0,5.976649e+03,1.078664e+04
24,12992601,G4A00290751301,2017-04-14,3597.0,SE,Accepted,3050.0,3597.0,2016-08-20,2017-04-14,237,547.0,218.824498,8.0,6.122148e+03,1.021176e+04
25,12992601,G4A00290751301,2017-04-27,3622.0,SE,Accepted,3050.0,3622.0,2016-08-20,2017-04-27,250,572.0,231.515579,8.0,6.401954e+03,1.009311e+04
26,12992601,G4A00290751301,2017-07-20,3679.0,SE,Accepted,3050.0,3679.0,2016-08-20,2017-07-20,334,629.0,312.310815,8.0,7.039911e+03,8.227596e+03
27,12992601,G4A00290751301,2017-08-17,3696.0,SE,Accepted,3050.0,3696.0,2016-08-20,2017-08-17,362,646.0,337.439620,8.0,7.230178e+03,7.820703e+03
28,12992601,G4A00290751301,2017-09-27,3715.0,SE,Accepted,3050.0,3715.0,2016-08-20,2017-09-27,403,665.0,375.982460,8.0,7.442831e+03,7.225425e+03
29,12992601,G4A00290751301,2017-12-21,3987.0,SE,Accepted,3050.0,3987.0,2016-08-20,2017-12-21,488,937.0,482.653488,8.0,1.048712e+04,7.930736e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481261,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6075.0,7442.0,2017-12-13,2018-06-16,185,1367.0,242.909795,8.0,1.529977e+04,2.298968e+04
1481262,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6075.0,7449.0,2017-12-13,2018-07-13,212,1374.0,251.603937,8.0,1.537812e+04,2.230893e+04
1481263,9362748704,G4A01767191201,2018-04-13,7368.0,SO,Accepted,6432.0,7368.0,2018-01-13,2018-04-13,90,936.0,146.295937,8.0,1.047592e+04,2.613683e+04
1481264,9362748704,G4A01767191201,2018-05-13,7423.0,SO,Accepted,6432.0,7423.0,2018-01-13,2018-05-13,120,991.0,171.746999,8.0,1.109150e+04,2.357186e+04
1481265,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6432.0,7442.0,2018-01-13,2018-06-16,154,1010.0,187.925246,8.0,1.130415e+04,2.195562e+04
1481266,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6432.0,7449.0,2018-01-13,2018-07-13,181,1017.0,196.619388,8.0,1.138249e+04,2.113022e+04
1481267,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,6797.0,7442.0,2018-02-13,2018-06-16,123,645.0,131.028240,8.0,7.218986e+03,2.010963e+04
1481268,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,6797.0,7449.0,2018-02-13,2018-07-13,150,652.0,139.722382,8.0,7.297332e+03,1.906299e+04
1481269,9362748704,G4A01767191201,2018-06-16,7442.0,SO,Accepted,7125.0,7442.0,2018-03-13,2018-06-16,95,317.0,83.878605,8.0,3.547936e+03,1.543894e+04
1481270,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7125.0,7449.0,2018-03-13,2018-07-13,122,324.0,92.572747,8.0,3.626281e+03,1.429787e+04
1481271,9362748704,G4A01767191201,2018-07-13,7449.0,SO,Accepted,7368.0,7449.0,2018-04-13,2018-07-13,91,81.0,51.432541,8.0,9.065704e+02,6.433635e+03
1481272,9363117808,G4K00293191701,2018-12-04,1882.0,NW,Accepted,979.0,1882.0,2018-06-15,2018-12-04,172,903.0,33.787339,8.0,1.010658e+04,1.091800e+05
1481274,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,183.0,831.0,2018-02-25,2018-06-25,120,648.0,112.937353,8.0,7.252563e+03,2.343941e+04
1481275,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,183.0,847.0,2018-02-25,2018-07-25,150,664.0,120.311636,8.0,7.431639e+03,2.254602e+04
1481276,9364510501,E6S06247081756,2018-06-25,831.0,EM,Accepted,519.0,831.0,2018-03-25,2018-06-25,92,312.0,69.061888,8.0,3.491975e+03,1.845549e+04
1481277,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,519.0,847.0,2018-03-25,2018-07-25,122,328.0,76.436171,8.0,3.671050e+03,1.753010e+04
1481278,9364510501,E6S06247081756,2018-07-25,847.0,EM,Accepted,730.0,847.0,2018-04-25,2018-07-25,91,117.0,40.385999,8.0,1.309491e+03,1.183489e+04
1481279,9365381207,G4K10362850201,2018-07-05,121549.0,EA,Accepted,21572.0,121549.0,2018-04-06,2018-07-05,90,99977.0,57.433733,8.0,1.118965e+06,7.111192e+06
1481280,9365381207,G4K10362850201,2018-07-29,21598.0,EA,Accepted,21572.0,21598.0,2018-04-06,2018-07-29,114,26.0,64.325320,8.0,2.909979e+02,1.651204e+03
1481281,9365381207,G4K10362850201,2018-08-06,121575.0,EA,Accepted,21572.0,121575.0,2018-04-06,2018-08-06,122,100003.0,66.477169,8.0,1.119256e+06,6.145396e+06
1481282,9365848802,G4A00135409901,2018-06-04,115748.0,SW,Accepted,15923.0,115748.0,2018-02-07,2018-06-04,117,99825.0,138.723412,8.0,1.117264e+06,2.939672e+06
1481283,9365848802,G4A00135409901,2018-06-08,15949.0,SW,Accepted,15923.0,15949.0,2018-02-07,2018-06-08,121,26.0,140.214048,8.0,2.909979e+02,7.575149e+02
1481284,9365848802,G4A00135409901,2018-07-05,115828.0,SW,Accepted,15923.0,115828.0,2018-02-07,2018-07-05,148,99905.0,148.447060,8.0,1.118159e+06,2.749318e+06
1481286,9366729002,G4W00525150701,2018-06-02,35296.0,WM,Accepted,34967.0,35296.0,2018-01-23,2018-06-02,130,329.0,163.717307,8.0,3.682243e+03,8.209386e+03
1481287,9366729002,G4W00525150701,2018-06-04,36236.0,WM,Accepted,34967.0,36236.0,2018-01-23,2018-06-04,132,1269.0,164.501997,8.0,1.420294e+04,3.151373e+04
1481288,9366729002,G4W00525150701,2018-06-07,36680.0,WM,Accepted,34967.0,36680.0,2018-01-23,2018-06-07,135,1713.0,165.635765,8.0,1.917228e+04,4.224863e+04
1481289,9366729002,G4W00525150701,2018-06-08,36712.0,WM,Accepted,34967.0,36712.0,2018-01-23,2018-06-08,136,1745.0,166.011859,8.0,1.953044e+04,4.294036e+04
1481290,9366729002,G4W00525150701,2018-07-03,135822.0,WM,Accepted,34967.0,135822.0,2018-01-23,2018-07-03,161,100855.0,173.364350,8.0,1.128792e+06,2.376550e+06
1481291,9366729002,G4W00525150701,2018-07-05,36496.0,WM,Accepted,34967.0,36496.0,2018-01-23,2018-07-05,163,1529.0,173.856314,8.0,1.711291e+04,3.592745e+04
1481292,9366729002,G4W00525150701,2018-08-06,36609.0,WM,Accepted,34967.0,36609.0,2018-01-23,2018-08-06,195,1642.0,181.167647,8.0,1.837764e+04,3.702558e+04

In [190]:
newjDF1.reset_index(drop=True, inplace=True)

In [226]:
newjDF1[newjDF1['meterPointIdentifier']==11006910]

,meterPointIdentifier,SerialNum,eventDttm,cumulative,LDZ,STAT,value,value1,date,date1,Delta_Date,deltaR,ALP,mrmr,UnitConvUsage,AQ
0,11006910,G4K00362451701,2018-06-18,996.0,SW,Accepted,0.0,996.0,2018-03-03,2018-06-18,107,996.0,100.020326,8.0,11147.457760,40679.952217
1,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,49806.0,51695.0,2016-12-28,2017-09-20,266,1889.0,265.584589,8.0,21142.116173,29056.175407
2,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,49806.0,53973.0,2016-12-28,2018-03-03,430,4167.0,512.599098,8.0,46638.008520,33208.940820
3,11006910,G4K01864940101,2017-09-20,51695.0,SW,Accepted,50806.0,51695.0,2017-03-14,2017-09-20,190,889.0,184.321343,8.0,9949.889507,19703.142408
4,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,50806.0,53973.0,2017-03-14,2018-03-03,354,3167.0,431.335852,8.0,35445.781853,29994.516608
5,11006910,G4K01864940101,2018-03-03,53973.0,SW,Accepted,51695.0,53973.0,2017-09-20,2018-03-03,164,2278.0,248.061622,8.0,25495.892347,37514.874859

In [192]:
print('number of records available',len(newjDF1))
print('number of MPRNs available',len(newjDF1['meterPointIdentifier'].unique()))

number of records available 1224201
number of MPRNs available 38466

In [193]:
FinalAQDf = newjDF1[['meterPointIdentifier','SerialNum','LDZ','date','date1','Delta_Date','value','value1','STAT','deltaR','mrmr','UnitConvUsage','ALP','AQ']]

In [194]:
FinalAQDf[FinalAQDf['meterPointIdentifier']==11006910]

,meterPointIdentifier,SerialNum,LDZ,date,date1,Delta_Date,value,value1,STAT,deltaR,mrmr,UnitConvUsage,ALP,AQ
0,11006910,G4K00362451701,SW,2018-03-03,2018-06-18,107,0.0,996.0,Accepted,996.0,8.0,11147.457760,100.020326,40679.952217
1,11006910,G4K01864940101,SW,2016-12-28,2017-09-20,266,49806.0,51695.0,Accepted,1889.0,8.0,21142.116173,265.584589,29056.175407
2,11006910,G4K01864940101,SW,2016-12-28,2018-03-03,430,49806.0,53973.0,Accepted,4167.0,8.0,46638.008520,512.599098,33208.940820
3,11006910,G4K01864940101,SW,2017-03-14,2017-09-20,190,50806.0,51695.0,Accepted,889.0,8.0,9949.889507,184.321343,19703.142408
4,11006910,G4K01864940101,SW,2017-03-14,2018-03-03,354,50806.0,53973.0,Accepted,3167.0,8.0,35445.781853,431.335852,29994.516608
5,11006910,G4K01864940101,SW,2017-09-20,2018-03-03,164,51695.0,53973.0,Accepted,2278.0,8.0,25495.892347,248.061622,37514.874859

In [195]:
FinalAQDf.to_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/wholefinalAQ.csv')

In [199]:
fDf = FinalAQDf[FinalAQDf['meterPointIdentifier']==11006910]

In [200]:
fDf

,meterPointIdentifier,SerialNum,LDZ,date,date1,Delta_Date,value,value1,STAT,deltaR,mrmr,UnitConvUsage,ALP,AQ
0,11006910,G4K00362451701,SW,2018-03-03,2018-06-18,107,0.0,996.0,Accepted,996.0,8.0,11147.457760,100.020326,40679.952217
1,11006910,G4K01864940101,SW,2016-12-28,2017-09-20,266,49806.0,51695.0,Accepted,1889.0,8.0,21142.116173,265.584589,29056.175407
2,11006910,G4K01864940101,SW,2016-12-28,2018-03-03,430,49806.0,53973.0,Accepted,4167.0,8.0,46638.008520,512.599098,33208.940820
3,11006910,G4K01864940101,SW,2017-03-14,2017-09-20,190,50806.0,51695.0,Accepted,889.0,8.0,9949.889507,184.321343,19703.142408
4,11006910,G4K01864940101,SW,2017-03-14,2018-03-03,354,50806.0,53973.0,Accepted,3167.0,8.0,35445.781853,431.335852,29994.516608
5,11006910,G4K01864940101,SW,2017-09-20,2018-03-03,164,51695.0,53973.0,Accepted,2278.0,8.0,25495.892347,248.061622,37514.874859

In [201]:
fDf[fDf['AQ']==fDf['AQ'].min()]

,meterPointIdentifier,SerialNum,LDZ,date,date1,Delta_Date,value,value1,STAT,deltaR,mrmr,UnitConvUsage,ALP,AQ
3,11006910,G4K01864940101,SW,2017-03-14,2017-09-20,190,50806.0,51695.0,Accepted,889.0,8.0,9949.889507,184.321343,19703.142408

In [202]:
minAQ = FinalAQDf.groupby(['meterPointIdentifier']).min().AQ
minAQ

meterPointIdentifier
11006910      1.970314e+04
12807108      3.583631e+04
12992601      2.609901e+03
15821701      7.872197e+03
16686210      1.178938e+04
16923209      7.997881e+02
17484506      5.659920e+04
18588310      9.208914e+03
19507704      2.069492e+04
19694202      1.833993e+04
21637200      6.332192e+03
22030705      6.565585e+04
44642804      1.509823e+03
45538904      4.772469e+03
46163106      2.449354e+04
48235901      1.284927e+03
48680305      1.593752e+04
48877100      1.431600e+04
49022810      6.026225e+03
49662510      1.008489e+04
49674203      9.669049e+04
49724203      1.468601e+04
49725205      2.065867e+03
49747305      1.264553e+02
50073406      1.112243e+04
50208100      7.240789e+02
50247806      6.178278e+03
50301101      3.867469e+04
50312106      2.568776e+04
50378103      1.957480e+04
                  ...
9353602910    3.566108e+03
9354021300    2.097461e+03
9354204510    1.063525e+03
9355169203    1.104421e+03
9355184300    6.839205e+02
9355511008    1.443569e+04
9355762707    4.243075e+02
9355779803    4.570607e+03
9356194600    6.173898e+03
9356667000    3.032228e+03
9358427001    1.143789e+03
9358493800    1.300332e+06
9358584601    7.092605e+02
9359292110    1.828315e+04
9359801801    1.773907e+04
9359889404    1.801768e+03
9360412200    2.730131e+06
9360811405    3.115654e+04
9360838302    6.297568e+03
9360847606    3.125647e+04
9361851602    1.267994e+03
9361989205    3.258074e+03
9361992800    4.720615e+03
9362188804    5.564616e+03
9362748704    1.785536e+03
9363117808    1.091800e+05
9364510501    1.183489e+04
9365381207    1.651204e+03
9365848802    7.575149e+02
9366729002    8.209386e+03
Name: AQ, Length: 38466, dtype: float64

In [203]:
FinalAQdf2 = pd.DataFrame({'meterPointIdentifier':minAQ.index, 'AQ':minAQ.values})
FinalAQdf2

       meterPointIdentifier            AQ
0                  11006910  1.970314e+04
1                  12807108  3.583631e+04
2                  12992601  2.609901e+03
3                  15821701  7.872197e+03
4                  16686210  1.178938e+04
5                  16923209  7.997881e+02
6                  17484506  5.659920e+04
7                  18588310  9.208914e+03
8                  19507704  2.069492e+04
9                  19694202  1.833993e+04
10                 21637200  6.332192e+03
11                 22030705  6.565585e+04
12                 44642804  1.509823e+03
13                 45538904  4.772469e+03
14                 46163106  2.449354e+04
15                 48235901  1.284927e+03
16                 48680305  1.593752e+04
17                 48877100  1.431600e+04
18                 49022810  6.026225e+03
19                 49662510  1.008489e+04
20                 49674203  9.669049e+04
21                 49724203  1.468601e+04
22                 49725205  2.065867e+03
23                 49747305  1.264553e+02
24                 50073406  1.112243e+04
25                 50208100  7.240789e+02
26                 50247806  6.178278e+03
27                 50301101  3.867469e+04
28                 50312106  2.568776e+04
29                 50378103  1.957480e+04
...                     ...           ...
38436            9353602910  3.566108e+03
38437            9354021300  2.097461e+03
38438            9354204510  1.063525e+03
38439            9355169203  1.104421e+03
38440            9355184300  6.839205e+02
38441            9355511008  1.443569e+04
38442            9355762707  4.243075e+02
38443            9355779803  4.570607e+03
38444            9356194600  6.173898e+03
38445            9356667000  3.032228e+03
38446            9358427001  1.143789e+03
38447            9358493800  1.300332e+06
38448            9358584601  7.092605e+02
38449            9359292110  1.828315e+04
38450            9359801801  1.773907e+04
38451            9359889404  1.801768e+03
38452            9360412200  2.730131e+06
38453            9360811405  3.115654e+04
38454            9360838302  6.297568e+03
38455            9360847606  3.125647e+04
38456            9361851602  1.267994e+03
38457            9361989205  3.258074e+03
38458            9361992800  4.720615e+03
38459            9362188804  5.564616e+03
38460            9362748704  1.785536e+03
38461            9363117808  1.091800e+05
38462            9364510501  1.183489e+04
38463            9365381207  1.651204e+03
38464            9365848802  7.575149e+02
38465            9366729002  8.209386e+03

[38466 rows x 2 columns]

In [204]:
FinalAQmerged = pd.merge(FinalAQDf,FinalAQdf2, how='inner', left_on=['meterPointIdentifier','AQ'], right_on = ['meterPointIdentifier','AQ'])

In [235]:
FinalAQmerged[FinalAQmerged['meterPointIdentifier']==202592009]

,meterPointIdentifier,SerialNum,LDZ,date,date1,Delta_Date,value,value1,STAT,deltaR,mrmr,UnitConvUsage,ALP,AQ
319,202592009,8009651S,NT,2017-04-10,2017-10-20,193,6677.0,6759.0,Accepted,82.0,14.0,2597.26812,179.960395,5267.841649

In [206]:
FinalAQmerged.to_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/minimumfinalAQ.csv')

In [70]:
# FinalAQmerged = pd.read_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/minimumfinalAQ.csv', dayfirst=True)
# del FinalAQmerged['Unnamed: 0']

In [236]:
FinalAQmerged[FinalAQmerged['meterPointIdentifier']==202592009]

,meterPointIdentifier,SerialNum,LDZ,date,date1,Delta_Date,value,value1,STAT,deltaR,mrmr,UnitConvUsage,ALP,AQ
319,202592009,8009651S,NT,2017-04-10,2017-10-20,193,6677.0,6759.0,Accepted,82.0,14.0,2597.26812,179.960395,5267.841649

In [208]:
IndustryAQ = pd.read_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/industry_AQ.csv',encoding = "ISO-8859-1")

In [237]:
IndustryAQ[(IndustryAQ['IND_MPRN']==202592009) & (IndustryAQ['IND_SerialNum']=='8009651S')]

      IND_MPRN IND_SerialNum  IND_AQ
324  202592009      8009651S   81923

In [239]:
IndustryAQ[IndustryAQ['IND_MPRN']==202592009]

      IND_MPRN IND_SerialNum  IND_AQ
324  202592009      8009651S   81923

In [220]:
IndustryAQ = IndustryAQ[['IND_MPRN','IND_SerialNum','IND_AQ']]
IndustryAQ

         IND_MPRN   IND_SerialNum  IND_AQ
0      1018758306  G4A00052939901   32911
1      1040707210          531651   26299
2      1066572604          568102   14906
3      1093436902  E6S06247311756   12702
4      1137821604  G4A03501860001   26019
5      1146445603          272066   25888
6      1281548900  G4K01003581708   22160
7      1315464710  G4K14293210401   18417
8      1469644703  G4A01825709901   18199
9      1475245405  G4K00442770101   20683
10     1478987701  G4A00152330501   11016
11     1542432209  G4A01675950101    9158
12     1576426500  G4A01854079901   22650
13     1578061900  G4K00255751201   29484
14     1586630707  E6S01735601456   12706
15     1605590910          548386   13247
16     1025883008  E6S01134271756    9367
17     1264606610  G4A04413950501   20523
18     1266103403  E6S05785131660   13137
19     1302797301  G4K02112820101   12918
20     1514090401          533449   24265
21     1122174105  E6S12110221760   20820
22     1298850200  G4KS0137541161    7540
23     4011496100  G4A00490011001   15241
24     4161809110          817497   32061
25     4180809802  E6S08275221556   13346
26     4180809802  E6S08275221556   13002
27     4192177201  G4A02195510501   28433
28     4212265908          326531   20501
29     4225965902          813075   12638
...           ...             ...     ...
45039  1135596108  E6S12061021660   26381
45040  1250757807          466979    9645
45041  1281678902  E6S11513511756   10688
45042  1465182109  E6S01361821556   19462
45043  1471184907  E6S04059831256    6071
45044  1485605606  G4A04457300601   15615
45045  1492242710  U6S01352951402   14035
45046  1511669801  G4W00258960601   22872
45047  1511669801  G4W00258960601   19914
45048  1518432300          794138   22062
45049  1580063005  G4W00003490602   15273
45050  1000091408  G4A00260731001   13804
45051  1040152606  G4A00960440401   26161
45052  1057200801  G4A03644840001   17648
45053  1290398504  G4A41006581702   16599
45054  1327902904  G4K11633830301   15344
45055  1327902904  G4K11633830301   15183
45056  1467939207        0111298S   25417
45057  1479755404  G4K12953000401   27291
45058  1482598800  G4K00536551201   33683
45059  1500711302  G4A01298720001   26146
45060  7632112802  G4K50019391706    7706
45061  8885091305  G4A50832800801   12232
45062  8885091305  G4A50832800801   13813
45063  9084810504  G4A50094430301   26119
45064  9085286709  G4W00548640201   20670
45065  9091178804  G4A50369710101   13332
45066  9144019001  G4A03715850801   12197
45067  9212012706  G4A50772810801   16574
45068  9303314605  G4K68164210714   13292

[45069 rows x 3 columns]

In [221]:
AQcomparisonDf = pd.merge(FinalAQmerged,IndustryAQ, how='inner', left_on=['meterPointIdentifier','SerialNum'], right_on = ['IND_MPRN','IND_SerialNum'])

In [240]:
AQcomparisonDf[AQcomparisonDf['meterPointIdentifier']==202592009]

,meterPointIdentifier,SerialNum,LDZ,date,date1,Delta_Date,value,value1,STAT,deltaR,mrmr,UnitConvUsage,ALP,AQ,IND_MPRN,IND_SerialNum,IND_AQ,AQdifference
208,202592009,8009651S,NT,2017-04-10,2017-10-20,193,6677.0,6759.0,Accepted,82.0,14.0,2597.26812,179.960395,5267.841649,202592009,8009651S,81923,76655.158351

In [223]:
AQcomparisonDf['AQdifference'] = AQcomparisonDf['IND_AQ'] - AQcomparisonDf['AQ']
AQcomparisonDf[AQcomparisonDf['meterPointIdentifier']==11006910]

,meterPointIdentifier,SerialNum,LDZ,date,date1,Delta_Date,value,value1,STAT,deltaR,mrmr,UnitConvUsage,ALP,AQ,IND_MPRN,IND_SerialNum,IND_AQ,AQdifference
0,11006910,G4K01864940101,SW,2017-03-14,2017-09-20,190,50806.0,51695.0,Accepted,889.0,8.0,9949.889507,184.321343,19703.142408,11006910,G4K01864940101,37972,18268.857592

In [224]:
AQcomparisonDf.to_csv('D:/Users/Aravindhan.P.Dev/OneDrive - So Energy/AQ calc/Results/ComparisonAQ.csv')